### ISSUE TITLE
Improve documentation of Subscriber::record and Subscriber::event

### ISSUE THREAD

**Issue by MSleepyPanda** [tokio-rs/tokio#1007]
## Subcrates

`tokio-trace-core`

## Description

Per https://github.com/MSleepyPanda/demo-subscriber/pull/1#discussion_r269270530.

The documentation doesn't explain when `Subscriber::record` is called. @hawkw gives a good example:
```rust
// "foo = 3" will be recorded if you call `record` on the `Attributes` passed to `new_span`.
// Since values are not provided for the `bar` and `baz` fields, the span's `Metadata` will
// indicate that it _has_ those fields, but values for them won't be recorded at this time.
let mut span = span!("my_span", foo = 3, bar, baz); 

// `Subscriber::record` will be called with a `Record` containing "bar = false"
span.record("bar", &false);

// `Subscriber::record` will be called with a `Record` containing "baz = "a string""
span.record("baz", &"a string");
```

While `Subscriber::event` is more obvious, providing an example wouldn't hurt.

**Comment by MSleepyPanda** [comment]
I will make a PR tomorrow :)

**Comment by hawkw** [comment]
Thanks, this can definitely be better documented.

I think it's worth mentioning in the docs that there is a distinction between "recording fields on a span" and "recording fields on an event within that span" --- the events refer to a particular moment in time, when a particular source code location was hit, within that span; while the span fields refer to the span _overall_.

**Comment by MSleepyPanda** [comment]
A few questions:
1. Is a span allowed to declare a field and never record its value, especially when it leaves the stack?
2. What is the desired behaviour when a span chooses to re-record a field?
3. Currently, the implementation silently ignores incorrect field names. Wouldn't panicing be an appropriate response here? While it doesn't affect the program itself, it should always be a logic bug that the end user should know of.

**Comment by hawkw** [comment]
@MSleepyPanda these are good questions, thanks:

>     1. Is a span allowed to declare a field and never record its value, especially when it leaves the stack?

Yes. Every instance of a given span is not _necessarily_ guaranteed to record all of the fields that span may contain.

>     2. What is the desired behaviour when a span chooses to re-record a field?

This is left up to the `Subscriber` implementation, though subscribers should generally expect that spans _may_ do this. Depending on how the subscriber formats or records data, it may wish to replace the prior value or display both. Ignoring a duplicate field is also _permitted_ but I wouldn't recommend it.

>     3. Currently, the implementation silently ignores incorrect field names. Wouldn't panicing be an appropriate response here? While it doesn't affect the program itself, it should always be a logic bug that the end user should know of.

At one point in time, the `record` function returned a `Result` in cases like this, but [we decided that was the wrong thing](https://github.com/hawkw/tokio-trace-prototype/issues/104). We didn't make it panic, since at that time, the `Subscriber` was responsible for determining whether a field is present on a span, and we thought panics coming from inside the subscriber implementation would be difficult to diagnose. 

Now that [`Span` handles in `tokio-trace` know their own fields](https://tokio-rs.github.io/tokio/doc/tokio_trace/span/struct.Span.html#method.has_field), I think panicking in this case would be more acceptable, since the panic would happen in `Span::record` and any stack trace would include the call site where the invalid field was provided. 

I'm somewhat of two minds as to whether or not panicking is the right thing to do here. I don't think it's acceptable for `tokio-trace-core` to ever panic if it can be avoided, since it might be used in software that must be highly reliable. Given that all we're doing is recording diagnostic data, it's probably better to lose some of that data than to actually crash the application. 

On the other hand, since the `tokio-trace` crate is loosely coupled to `tokio-trace-core`, it's possible to implement an alternative instrumentation API that uses the same primitives and provides similar APIs to `tokio-trace` with alternative behaviour, so it's somewhat more acceptable to panic in `tokio-trace`. 

On the third hand, the best of both worlds might be to have a `debug_assert!` that a span on which `record` is called contains the named field. This way, we would crash in development in the face of such a logic error, but if the incorrect `record` call was somehow not hit in dev and made it into the wild, we wouldn't bring down the application due to a logic error in diagnostics code. We might consider printing a warning in release mode instead...
