### ISSUE TITLE
tokio: provide future / stream / sink helpers

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1225]
Currently, the goal is to update `master` to use `std::future`. There currently are no future helpers provided by `std`. However, there are helpers provided by `futures-rs` and other locations.

`tokio` must decide how it will depend on external crates for both private and public usage as well as what helpers `tokio` will provide itself.

### Fix TODO

This list tracks places in the code base that had temporary code applied to get things working and need a second pass.

- [ ] tokio-threadpool/tests/threadpool.rs
- [ ] tokio-timer/tests/hammer.rs
- [ ] tokio-timer/tests/timeout.rs

Refs: rust-lang-nursery/futures-rs#1701, rust-lang-nursery/futures-rs#1700

**Comment by carllerche** [comment]
Switch to futures-sink: #1244

**Comment by rubdos** [comment]
This sounds like it's "decided" to use `futures-preview` then? A Stream trait would be very useful, since even the examples cannot be cleanly written without one. Even if you wrote https://github.com/tokio-rs/tokio/pull/1242 (`async fn accept()`) to avoid importing `Stream`, iterating over items in `Framed` also becomes cumbersome! (Found out while rewriting examples)

**Comment by carllerche** [comment]
As of now, Tokio will add a public dependency on the `Stream` / `Sink` traits. Internals, tests, and examples can use the helpers for those traits provided in `futures-util`.
