### ISSUE TITLE
Mock timer

### ISSUE THREAD

**Issue by olix0r** [tokio-rs/tokio#127]
Whenever tokio grows a timer trait, it should also grow a mock timer implementation.

In order to avoid flakey tests, we'll need a way to do something like the following:

```rust
let (timer, clock) = tokio::timer::mock(...);

let fut = timer.sleep(Duration::from_secs(30));
assert!(fut.poll()?.is_not_ready());

clock.advance(Duration::from_secs(29));
assert!(fut.poll()?.is_not_ready());

clock.advance(Duration::from_secs(1));
assert!(fut.poll()?.is_ready());
```

**Comment by tailhook** [comment]
This isn't hard. But it would require everything to be generic over the `<T: Timeout>` that isn't viable. So we need clock-advance behavior in standard timeout/interval things.

As I have already said before we actually need a patchable clock source which both builtin Timeout/Interval using it and other code, effectively replacing `Instant::now` everywhere.

**Comment by carllerche** [comment]
As of now, I don't think that a Timer trait is correct, in part because it could never efficiently be made a trait object.

I do believe being able to take control of the clock / time source can be added in the real timer without too much trouble, achieving the same result (similar to what @tailhook is suggesting).

**Comment by carllerche** [comment]
Closing in favor of #146.
