### ISSUE TITLE
::tokio_executor::SpawnError should be able to give the boxed future back

### ISSUE THREAD

**Issue by danielhenrymantilla** [tokio-rs/tokio#1353]
The current (`0.1.8`) API of `::tokio_executor::Executor` API does not allow to get the future back when `spawn()` fails. This leads to having to rely on `.status()`, which is suboptimal due to, among other things, [TOC/TOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use)

**Comment by carllerche** [comment]
Thanks for the report.

This is intentional. Using `status` is best effort. There is no guarantee that after you spawn the task is run, even if it were to give you the task back. If you require more rigorous guarantees, you can implement a layer on top of spawn.

If you can provide a compelling argument as to why this is the incorrect design, I can reopen the issue.
