### ISSUE TITLE
tokio-signal: Support SIGCHLD

### ISSUE THREAD

**Issue by naftulikay** [tokio-rs/tokio#1422]
## Version

`master`

## Platform

```
Linux cosmos 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Subcrates

`tokio-signal`

## Description

I'm writing a process manager with Tokio, and I'd like to be able to use `tokio-signal` to respond to process signals. It's important that I be able to catch `SIGCHLD` to keep track of when processes die so that I can take an action based on this.

I'm not sure if this is a Linux-specific signal or whether it is used elsewhere.

If supporting this specific signal is out of scope for `tokio-signal`, perhaps another way to handle arbitrary signals would be useful, allowing users to register signal handlers for arbitrary signal numbers unique to their platform.

**Comment by ipetkov** [comment]
Hi @naftulikay, it's definitely possible to do so today, in fact, that's exactly what `tokio-process` [does under the hood](https://github.com/tokio-rs/tokio/blob/756606a58be2ad29c33752873d2c5c3c2f7a1d71/tokio-process/src/unix/mod.rs#L102)! Granted, it's not very obvious today that it is supported since it requires creating the Unix specific `Signal` type and passing in `libc::SIGCHLD`.

We're planning on making this interface easier to use without having to import `libc` (tracked in #1243), so I'm going to close this out as a duplicate. Feel free to reopen if you have other questions!
