### ISSUE TITLE
TcpStream: connect() from net::TcpStream

### ISSUE THREAD

**Issue by jedisct1** [tokio-rs/tokio#1543]
## Version

0.2.0-alpha.4

## Description

Currently, the only way to create a `TcpStream` is by creating a listener, or calling `connect()`.

But no options can be set before calling `connect()`. In particular, we can't `bind()` the socket to a source address.

That can be done by preparing a `net::TcpStream`, but while that can be converted to a tokio `TcpStream`, it's then impossible call `connect()` on it since tokio's `connect()` is not an instance method.

That can be solved by having a `connect_from_std()` method.

**Comment by carllerche** [comment]
Ok, I would prefer going that route. I think the best strategy would be to also add `TcpSocket` to mio. So, we probably should wait until tokio has migrated to mio master to move on this.

**Comment by vorner** [comment]
I've also had this need (and found the [well hidden](https://github.com/tokio-rs/tokio/blob/2f91c85ad80c1311225ef482f6feb3c18b441edc/tokio-net/src/tcp/stream.rs#L154) `connect_std`).

I can also imagine wanting to set some less standard options before connect, so having the socket in some kind that I can do `AsRawFd` on as an escape hatch would be nice.

Would it make sense to some to have some `connect_from_net2_builder` instead of `connect_std` (with a feature flag, to not pull in net2 indiscriminately)?

**Comment by carllerche** [comment]
This `TcpSocket` fn could include a `from_std` function that takes an unbound / unconnected std socket. This would let you use net2.

**Comment by zonyitoo** [comment]
@carllerche Is `TcpSocket` still in plan? I want to call `bind` before `connect`.

If `TcpSocket` requires lots of work, I propose a `bind_connect` method:

```rust
fn bind_connect<A: ToSocketAddrs, T: ToSocketAddrs>(bind_addr: A, target_addr: T) -> io::Result<TcpStream>;
```

**Comment by Darksonn** [comment]
For now you can do this by using [`TcpStream::from_std`][1]. If this is added to mio, feel free to open a new issue here.

[1]: https://docs.rs/tokio/0.2/tokio/net/struct.TcpStream.html#method.from_std

**Comment by vorner** [comment]
Reading the example and API in the docs, I'm not entirely sure this fulfills the needs. It expects the socket to be already connected, right? But connect on the std socket is blocking which might pose a problem for using that API (if one needs to initiate a lot of connections, then they'd have to deal with a thread pool for just setting up the connections).

I've actually hit the problem when I needed a stress-test tool and the reason I had to set the source IP was because I was creating so many connections during a short time that I was running out of source ports. I think not even big thread pools would be entirely appropriate for that.

**Comment by Darksonn** [comment]
You can create the socket using the `socket2` crate as described [here](https://stackoverflow.com/questions/59298027/how-to-bind-on-tcp-client-side-in-rust-tokio/59916539#59916539).

**Comment by vorner** [comment]
I haven't tried to rewrite the code from back then, but I'd guess that having 1000 connection requests in the flight at the same time would not be possible with it.
