### ISSUE TITLE
Configurable timer instance

### ISSUE THREAD

**Issue by vorner** [tokio-rs/tokio#1566]
Hello

Playing a bit with tokio 0.2.0-alpha.4 (https://vorner.github.io/2019/09/15/play-with-new-async.html), I've hit the fact the timer instance didn't support the precision I needed.

So I wonder, would it make sense to:
* Make the [Timer](https://docs.rs/tokio-timer/0.3.0-alpha.4/tokio_timer/timer/struct.Timer.html) configurable as in what the smallest unit in the wheel is.
* Make the runtime's `Builder` take a timer instance/closure to create one?

**Comment by LucioFranco** [comment]
@vorner I believe the timer can't go below `1ms` due to limitations with epoll and its timeout. I think the best case here is to just use a different timer implementation like https://github.com/jonhoo/tokio-os-timer? We might be able to include some of this within tokio too, not sure though.

**Comment by vorner** [comment]
I see. I thought it was only a performance consideration about the timer wheel, but the epoll seems to be a technical problem :-(. Using an external crate is fine if it's completely different implementation.

What to do with this issue? I'm fine with closing it, I don't know if you want to keep tracking it as a possible consideration for improvement. Or maybe just add a link for alternatives into the timer's docs?

**Comment by jonhoo** [comment]
I think the real solution here is to go with https://docs.rs/async-timer/. It gets around the 1ms limitation by not using `epoll`'s timeout argument, and instead relying OS-level timer primitives.

**Comment by carllerche** [comment]
I’m happy to make changes to tokio-timer if it can be done sanely in a cross platform way and doesn’t impact the coarse timeouts in a measurable way. The biggest issue is windows I believe.

**Comment by jonhoo** [comment]
We should loop in @DoumanAsh here too

**Comment by DoumanAsh** [comment]
There is no easy way to get precise tiemers on windows as it rely on thread pool internally.

As @jonhoo mentioned I have own crate for OS timers.
On epool/kqueue environments you can enable these timers with `tokio_on` features.
I didn't do measurements, but I believe they should be what you need.
With `tokio` it only relies on reactor, which makes runtime itself irrelevant

But question remains if we need to complicate tokio timer with configuration of precision?
Which may not be even applicable to some platforms.
Rather than that, I think having alternative implementation would be better, even in form of 3pp crate.

**Comment by carllerche** [comment]
Anyway, to re-iterate, I'm open to supporting higher precision, but there would need to be a proposal for how it should be implemented on all platforms.

Since this issue has stagnated some, I will close it for now. If someone is motivated to champion this to completion, we can open a new issue and reference this.
