### ISSUE TITLE
How to send bytes::bytes::Bytes by futures:stream::Stream?

### ISSUE THREAD

**Issue by hanusek** [tokio-rs/tokio#1676]
I'm trying write a TCP server based on Tokio's example.

When I try to send the buffer, the compiler returns error 0277.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c4eb8cc62dd87334fb0bc73f9b74ef3d

## Version
tokio 0.1.22
Bytes  0.4.12

## Platform
Linux x86_64

## Code

```
extern crate tokio; // 0.1.22

use tokio::codec::{BytesCodec, Decoder};
use tokio::net::TcpListener;
use tokio::prelude::*;

use bytes::Bytes; // 0.4.12

fn main() {
    let addr = "0.0.0.0:1502".parse().unwrap();
    let mut socket = TcpListener::bind(&addr).unwrap();

    let done = socket
        .incoming()
        .map_err(|e| println!("failed to accept socket; error = {:?}", e))
        .for_each(move |socket| {
            let framed = BytesCodec::new().framed(socket);
            let (writer, reader) = framed.split();

            let processor = reader
                .for_each(move |bytes| {
                    println!("bytes: {:?}", bytes);
                    let mut data_to_send = [0 as u8; 1024];
                    let buf = Bytes::from(&data_to_send[..1024]);
                    writer.send_all(&mut buf);
                    Ok(())
                })
                .and_then(|()| Ok(()))
                .or_else(|err| Err(err))
                .then(|result| Ok(()));
            tokio::spawn(processor)
        });
    tokio::run(done);
}
```
## Error

> error[E0277]: the trait bound `bytes::bytes::Bytes: tokio::prelude::Stream` is not satisfied
>   --> src/main.rs:25:28
>    |
> 25 |                     writer.send_all(&mut buf); // ERROR : E0277
>    |                            ^^^^^^^^ the trait `tokio::prelude::Stream` is not implemented for `bytes::bytes::Bytes`
>    |
>    = note: required because of the requirements on the impl of `tokio::prelude::Stream` for `&mut bytes::bytes::Bytes`

**Comment by miquels** [comment]
`send_all` is a method on a `Sink`, that takes a `Stream` argument. You do not have a `Stream`; by using `for_each`, you only loop over all items in the stream.

Try using `map` instead of `for_each`, and return a `Bytes` value from that `map` closure. That will simply transform the stream from an input value to an output value. You can then `spawn(writer.send_all(processor))`.

(or, actually, `tokio::spawn(writer.send_all(processor).map(|_|()).map_err(|_|()))` because of the need to pass a `Future<Item=Result<(), ()>` to `tokio::spawn`.
