### ISSUE TITLE
tokio "fs" feature should depend on tokio-io

### ISSUE THREAD

**Issue by svartalf** [tokio-rs/tokio#1693]
With the following `Cargo.toml` dependency (latest [HEAD](https://github.com/tokio-rs/tokio/commit/227533d456fe32e48ffcd3796f1e6c8f9318b230) at the moment of creating this issue)

```toml
[dependencies.tokio]
git = "https://github.com/tokio-rs/tokio.git"
rev = "227533d456fe32e48ffcd3796f1e6c8f9318b230"
default-features = false
features = ["fs"]
```

compilation fails because fs routines are using `tokio-io` sub-crate, which is excluded by features selection:

```
$ cargo +nightly check
    Checking tokio v0.2.0-alpha.6 (https://github.com/tokio-rs/tokio.git?rev=227533d456fe32e48ffcd3796f1e6c8f9318b230#227533d4)
error[E0432]: unresolved import `tokio_io`
 --> /home/svartalf/.cargo/git/checkouts/tokio-377c595163f99a10/227533d/tokio/src/fs/file.rs:9:5
  |
9 | use tokio_io::{AsyncRead, AsyncWrite};
  |     ^^^^^^^^ use of undeclared type or module `tokio_io`

error[E0432]: unresolved import `tokio_io`
 --> /home/svartalf/.cargo/git/checkouts/tokio-377c595163f99a10/227533d/tokio/src/fs/blocking.rs:3:5
  |
3 | use tokio_io::{AsyncRead, AsyncWrite};
  |     ^^^^^^^^ use of undeclared type or module `tokio_io`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `tokio`.
```

I suppose that `fs` feature should enable `io` feature too?

**Comment by taiki-e** [comment]
The CI for each feature gate does not seem to work because the default feature is enabled by dev-dependencies. I believe I know a workaround for this, so will send pr.
https://github.com/tokio-rs/tokio/blob/227533d456fe32e48ffcd3796f1e6c8f9318b230/tokio-test/Cargo.toml#L23
https://github.com/tokio-rs/tokio/blob/227533d456fe32e48ffcd3796f1e6c8f9318b230/tokio/Cargo.toml#L114

Probably it needs to run the test only once with `all-features` and change it to run only `cargo check` for each feature.

https://github.com/tokio-rs/tokio/blob/227533d456fe32e48ffcd3796f1e6c8f9318b230/ci/azure-test-stable.yml#L36
https://github.com/tokio-rs/tokio/blob/227533d456fe32e48ffcd3796f1e6c8f9318b230/ci/azure-test-stable.yml#L56
