### ISSUE TITLE
reqwest stalls in locally-spawned task when "full" feature is not selected

### ISSUE THREAD

**Issue by dwrensha** [tokio-rs/tokio#2057]
## Version
```
[dependencies]
reqwest = "0.10"
tokio = { version = "0.2", features = ["net", "rt-util"] }
```

## Platform
```
Darwin niobium-2.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```

(I've also seen the below-described behavior on Linux.)

## Description

```rust
use tokio::sync::oneshot::channel;

fn main() {
    let mut rt = tokio::runtime::Runtime::new().unwrap();
    let local = tokio::task::LocalSet::new();
    let () = local.block_on(&mut rt, async move {
        let (send, recv) = channel();
        let _ = tokio::task::spawn_local(async {
            println!("making request... ");
            let resp = reqwest::get("http://www.rust-lang.org").await?;
            println!("got resp");
            let bytes = resp.bytes().await?;
            println!("got bytes {:?}", bytes);
            send.send(()).unwrap();
            Ok::<(), Box<dyn std::error::Error>>(())
        });

        recv.await.unwrap();
    });
}
```

I was hoping this program would make the HTTP request and then terminate. Instead it gets stuck after printing "making request...".

According to @carllerche, this looks like a bug.

If I add the "full" feature to `tokio`, then the program does terminate as hoped.

I suspect `reqwest` is spawning a task and my program is failing to execute it. That actually seems kind of reasonable (if inconvenient) to me, as I never call `rt.block_on()`. However, I don't know enough about `tokio::runtime::Runtime` and `tokio::task::LocalSet` to know what to expect.

**Comment by carllerche** [comment]
More specifically, this only happens when using `LocalSet` **with** the basic scheduler. I tried the repro w/ only the basic scheduler and it works. My guess is there is either a lost wake up or the `LocalSet` does not correctly poll the basic scheduler when a notification is received.

**Comment by hawkw** [comment]
Okay, I know what's going on here. 

When a task in a `LocalSet` is scheduled, we first check if the `LocalSet` is considered "current". If it is, we push the task to the local run queue. Otherwise, if the task was notified from outside the local set, we push the task to the remote run queue _and wake the future that runs the `LocalSet`_:
https://github.com/tokio-rs/tokio/blob/0193df3a593cb69d23414109118784de2948024c/tokio/src/task/local.rs#L344-L353

The rationale behind this is that if the `LocalSet` is "current", we are currently polling its tasks, and so we don't need to wake up the `LocalSet` itself, unless one of its tasks yields. 

The issue here is the way we determine if the `LocalSet` is current:
https://github.com/tokio-rs/tokio/blob/0193df3a593cb69d23414109118784de2948024c/tokio/src/task/local.rs#L385-L394
we do this by testing if a thread-local variable contains a pointer to the local set. However, that thread-local is set by the `Scheduler::with` function, which is called here:
https://github.com/tokio-rs/tokio/blob/0193df3a593cb69d23414109118784de2948024c/tokio/src/task/local.rs#L287-L288
Note how the local set is considered "current" for the duration of the call to `block_on`, _not_ just while we are polling the tasks spawned on the local set. 

This explains why this issue only occurs on the basic scheduler, and not on the thread pool: on the threadpool, the task created by `reqwest` using `tokio::spawn` are run on a worker thread, _not_ on the thread that calls `block_on`, so when they notify the local task, the `LocalSet` does _not_ consider itself current, and it wakes the future that drives its tasks. However, when running on the basic scheduler, the other tasks spawned on the runtime _are_ running on the same thread. Because we are considered "current" as long as we are inside of the call to `block_on`, when a task running outside the `LocalSet` on the _same_ thread notifies a task inside the `LocalSet`, the local task is not woken.

I confirmed this is the case by testing the repro against my PR #1971. This PR changes the `LocalSet` so that `Scheduler::with` is only called when actively polling local tasks, here:
https://github.com/tokio-rs/tokio/blob/27a474bb9772a40fc553e45c58a7ccb363a1fc87/tokio/src/task/local.rs#L369
and here:
https://github.com/tokio-rs/tokio/blob/27a474bb9772a40fc553e45c58a7ccb363a1fc87/tokio/src/task/local.rs#L402-L414

On #1971, the repro code runs to completion, prints the response body, and exits, confirming the above theory.
