### ISSUE TITLE
tokio-io seem to break API

### ISSUE THREAD

**Issue by ignatenkobrain** [tokio-rs/tokio#206]
```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
   --> src/reactor/poll_evented.rs:276:39
    |
276 |         if let Async::NotReady = self.poll_read() {
    |                                       ^^^^^^^^^ expected 1 parameter
```

We still didn't update tokio-core to latest version, but we did that with tokio-io. Turns out that new tokio-io causes old tokio-core to not build. I think for this you need to bump to 0.2.. But don't know for sure.

**Comment by carllerche** [comment]
Thanks for the report. I pushed a version of tokio-core with the fix.

The underlying issue here is that adding *any* function, type, or module to a library or std could result in a breaking change somewhere. I also believe that the "backwards compatible" policy that rust-lang uses permits adding new fns (otherwise, virtually every every crate release would be a breaking change).

In this case, I should have caught the issue earlier, but for some reason the tokio-core PR was passing up until i released tokio-io. I pushed a patch for tokio-core to resolve the issue. The specific issue probably won't show up in other downstream crates / apps.

**Comment by ignatenkobrain** [comment]
I don't think it's a new function, but rather change in arguments for `poll_read()`

**Comment by ignatenkobrain** [comment]
But anyway, just wanted to heads up. I am updating whole tokio stack in Fedora now.

**Comment by carllerche** [comment]
It's a new fn added to `AsyncRead` which conflicts with an existing fn on `PollEvented`.

Rust itself is dealing with this problem with `Iterator::flatten` vs. the fn in the itertools crate.

There isn't a good answer right now.
