### ISSUE TITLE
Unclear on when to (not) use split()

### ISSUE THREAD

**Issue by vojtechkral** [tokio-rs/tokio#2154]
## Version

```
├── tokio v0.2.8
│   └── tokio-macros v0.2.3
└── tokio-util v0.2.0
    └── tokio v0.2.8 (*)
    └── tokio v0.2.8 (*)
```

## Platform
N/A

## Description

Hi.
I've been kind of fighting with TCP stream splitting (cf. #1108 , #1521) for some time now and I'm wondering if I'm even using Tokio right at all. Our usecase is implementation of message-oriented protocols where messages don't necessarily follow the request/response pattern. Some messages do, some don't, and there can also be multiple request/response "threads" interleaved in one connection. The messages aren't generally large in size, but we're looking for low latency if possible.

We've been (generally, sans some details) using the pattern where TCP strams are `split()` and two tasks per connection are created, one waits on incomming network frames and processes them into application state, the other waits on frames produced by application state and writes them onto the TCP stream. But I've recently started switching to one task that uses `select! { ... }` instead, trying to avoid the problems with splitting.

The single task approach seems generally simpler to implement and seems to lend more easily to stuff like graceful shutdown, encrpytion, reconnecting, backpressure propagation/resolution etc. OTOH I was worried whether this might potentially decrease performance.

Is there some general advice on this?
Thanks!

**Comment by LucioFranco** [comment]
One task per TcpStream is generally the norm here.

**Comment by ultrasaurus** [comment]
I might not be fully understanding the context here, but in network programming (in other languages/platforms) I've found that it is quite common to have a write thread and a read thread, since they are often doing very different work and for many applications code can be structured so there is little or no contention.

**Comment by LucioFranco** [comment]
@ultrasaurus the difference here is that you can multiplex IO on the same thread since io calls are not blocking. While in a threaded context all IO calls are blocking and thus to get some way to multiplex requests you need to separate your io.

In general though the idea is to support handling IO on a single task but it doesn't hurt that much to use two. I think things like h2 and hyper don't split iirc.

**Comment by Darksonn** [comment]
I think that if splitting the stream into two independent tasks makes sense for your application, go ahead and do that, although I think you should prefer to keep the halves in the same task using `join!` or `try_join!` as that allows you to use the lifetime based split, which has no runtime cost.

**Comment by Darksonn** [comment]
That said, now that #2270 has been merged, this is less important. The owned split does _still_ cost creating an `Arc`, though.
