### ISSUE TITLE
Feature request: await a set of Unix signals

### ISSUE THREAD

**Issue by nvzqz** [tokio-rs/tokio#2159]
First off: I _love_ that Tokio offers the ability to `.await` a Unix signal. I'm writing a Hyper server and it's made graceful shutdown extremely easy to implement. Kudos for this feature! 💛

---

I believe it would be more efficient and cleaner if the API provided a way to `.await` a set of signals simultaneously. This would probably internally map to having the same raw signal handler for all signals in the set.

Currently, this is how I'm catching otherwise-terminating signals in [`with_graceful_shutdown`]:

```rust
async fn handle_all() -> tokio::io::Result<()> {
    futures::future::select_all(vec![
        signal(SignalKind::alarm())?.next(),
        signal(SignalKind::hangup())?.next(),
        signal(SignalKind::interrupt())?.next(),
        signal(SignalKind::quit())?.next(),
        signal(SignalKind::terminate())?.next(),
        signal(SignalKind::user_defined1())?.next(),
        signal(SignalKind::user_defined2())?.next(),
    ]).await;

    Ok(())
}
```

This feels very inefficient and clunky for handling multiple signals at once.

## 0.2 API

For `tokio-signal` 0.2, I propose:

```rust
pub fn signal_set<I>(kinds: I) -> SignalSet
    where I: IntoIterator<Item = SignalKind>;

pub struct SignalSet {
    // private fields
}

impl Debug for SignalSet { ... }
impl Stream for SignalSet { ... }

impl SignalSet {
    pub async fn recv(&mut self) -> Option<()>;

    pub fn poll_recv(&mut self, cx: &mut Context) -> Poll<Option<()>>;
}
```

## 0.3 API

For `tokio-signal` 0.3, I propose:

```rust
pub struct SignalSet {
    // private fields
}

impl Debug for SignalSet { ... }
impl Stream for SignalSet { ... }

impl SignalSet {
    pub fn new<I>(signals: I) -> Result<SignalSet>
        where I: IntoIterator<Item = c_int>
    {
        SignalSet::with_handle(signals, &Handle::default())
    }

    pub fn with_handle<I>(signals: I, handle: &Handle) -> Result<SignalSet>
        where I: IntoIterator<Item = c_int>;
}
```

[`with_graceful_shutdown`]: https://docs.rs/hyper/0.13.1/hyper/server/struct.Server.html#method.with_graceful_shutdown

**Comment by LucioFranco** [comment]
I'd be interested if there was a method to use a builder

```rust
let mut signals = Signals::builder()
	.alarm()
	.hangup()
	.quit()
	.build();

signals.next().await;
```

I feel like this would be the easiest api to consume?

**Comment by nvzqz** [comment]
Using the builder pattern here would be great. I was basing the styles off of how the current APIs look like.

**Comment by davidbarsky** [comment]
A `select!` macro (like the one that just landed) could be a compelling alternative interface: https://tokio-rs.github.io/tokio/doc/tokio/macro.select.html.

At first glance, I think I'd prefer a `select!` over a builder because it makes the nature of the operation a bit more explicit, I think. That being said, I don't know! I don't feel strongly about that.

**Comment by LucioFranco** [comment]
@davidbarsky well Im kinda thinking in general with signals you handle them all in the same place so a builder that could produce a single stream could be helpful imo.

**Comment by nvzqz** [comment]
@davidbarsky Unix allows for setting the same handler for multiple signals. So having one type to await a signal set would allow for this optimization. I haven't had the time to look into how this is currently done internally.

**Comment by ipetkov** [comment]
The internals work by registering a signal handler with the OS which sets an appropriate flag any time a signal is received. All signal listeners are woken up, and they cooperatively dispatch any pending signals based on the flags that were set earlier.

Even if we were to support a `SignalSet`, the signal delivery *architecture* will probably remain the same, although having a `SignalSet` API *could* let us optimize things by using a single channel slot for the whole set rather than one slot per signal.

**Comment by carllerche** [comment]
@ipetkov what action, if any, needs to be taken to close this issue?

**Comment by ipetkov** [comment]
Given that

1. the underlying signal delivery architecture will not change (due to complications with deregistering signal handlers)
1. we can use `tokio::select!` across a set of fixed signals
1. we can use `FuturesUnordered` across a dynamic set of signals

I do not think we need to introduce new `tokio` APIs especially with 1.0 looming over us.

I *do* see the benefits of having a builder-like convenience API, and I believe `tokio-util` would be a better place to explore open questions such as:

- should a `SignalSet` (or equivalent) function as a stream or a one-off future which fires when satisfied?
- should the events resolve when *any* or when *all* configured signals are received? do callers need *both* abilities?
- does the caller need to distinguish which signal was actually received?

I don't have any personal leanings towards any potential answer of these questions, so I'd be curious to hear more on what consumers would like to see
