### ISSUE TITLE
Question: Read upto X bytes form stream, where X is GBs in size?

### ISSUE THREAD

**Issue by cheako** [tokio-rs/tokio#2173]
## Version
any/2.10

## Platform
4.19.0-6-cloud-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

## Description
Relates to: https://github.com/seanmonstar/warp/issues/414
Code: https://gitlab.com/cheako/files-rs/blob/947b4422fefb58fb3aa52c80b320994633a19e18/src/freenet.rs#L51
I have a DB(for simplicity) TcpStream where the next X bytes will be the contents of a file and this file could be GBs in size.  I'm attempting to upload this file via Warp, so I'm implementing ```futures_core::Stream```.  In the implementation ```fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Result<Bytes, Box<dyn std::error::Error + 'static + Send + Sync>>>>``` is the prototype.  I don't want to allocate the size of the file.  On Linux large allocations are OK so long as one does not write to the allocation, so some kind of uninitialized slice might work.  Off topic, the OOM killer is only invoked on assignment: ```*x = y;``` 
 Scary huh!  Back to the issue I'm looking to poll the stream for as many bytes are currently pending, but stopping at this arbitrary boundary of EOF.

Any thoughts?

**Comment by cheako** [comment]
I did this, the data I get is good, don't know if the memory is being accessed. 
 https://gitlab.com/cheako/files-rs/blob/96145297a4837b00476e216741ba28a3a69f6f96/src/freenet.rs#L53-72

**Comment by Darksonn** [comment]
Are you simply trying to convert an `AsyncRead` (i.e. the `TcpStream`) into a stream of `Bytes`? The `tokio-util` crate provides a type called [`FramedRead`][1], which does exactly this if given a [`BytesCodec`][2].

Please be aware that this

    let buffer: Vec<MaybeUninit<u8>> = (0..num_bytes.get())
        .map(|_| unsafe { MaybeUninit::uninit().assume_init() })
        .collect();
    let mut buffer = unsafe { mem::transmute::<_, Vec<u8>>(buffer) };

is undefined behaviour. You have to actually initialize the memory before converting it into a `Vec<u8>`. Note also that your `MaybeUninit::uninit().assume_init()` actually first creates a `MaybeUninit<MaybeUninit<u8>>` and converts that to `MaybeUninit<u8>` with `assume_init`. Note finally that you can create a `Vec<MaybeUninit<u8>>` simply by combining `Vec::with_capacity` with `Vec::set_len`.

I recommend just using `tokio-codec` for this, however this is a good way to proceed if you were to make your own `Stream`. For example, I recommend using [`poll_read_buf`][3] instead of that unsafe snippet.

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        if let Some(num_bytes) = self.bytes_left {
            use std::mem::{self, MaybeUninit};
            use tokio::io::AsyncRead;
            let mut buffer: Vec<u8> = Vec::with_capacity(1024);
            match self.stream.as_mut().poll_read_buf(cx, &mut buffer) {
                Poll::Ready(Ok(0)) => {
                    // This only happens on EOF
                    use std::io::{Error, ErrorKind};
                    let e = Error::new(ErrorKind::UnexpectedEof, "File ended early");
                    Poll::Ready(Some(Err(Box::new(e))))
                },
                Poll::Ready(Ok(size)) => {
                    let bytes_remaining = num_bytes.get() - size;
                    self.bytes_left = NonZeroUsize::new(bytes_remaining);
                    Poll::Ready(Some(Ok(Bytes::from(buffer))))
                },
                Poll::Ready(Err(e)) => Poll::Ready(Some(Err(Box::new(e)))),
                Poll::Pending => Poll::Pending,
            }
        } else {
            Ready(None)
        }
    }

Note that `tokio-codec` is more efficient than this, as it will make use of the fact that you can have several `Bytes` into the same allocation — it will return the part that was read, and then use the rest of that allocation in the next read.

[1]: https://docs.rs/tokio-util/0.2/tokio_util/codec/struct.FramedRead.html
[2]: https://docs.rs/tokio-util/0.2/tokio_util/codec/struct.BytesCodec.html
[3]: https://docs.rs/tokio/0.2.10/tokio/io/trait.AsyncRead.html#method.poll_read_buf
