### ISSUE TITLE
Wrong documentation for Command::output()

### ISSUE THREAD

**Issue by gralpli** [tokio-rs/tokio#2235]
## Version

0.2.11

## Description

The documentation for the `tokio::process::Command::output()` method states that: “If this future is dropped before the future resolves, then the child will be killed, if it was spawned.” This is only true if `kill_on_drop(true)` was called before.

The same might apply for the docs of the `Command::status()` method.

**Comment by gralpli** [comment]
Also: The killed child process remains as a zombie until the application is exited. This should at least be stated in the docs (better: the child should automatically be reaped).

I'd also wish for a `child_process.terminate()` function in addition to `child_process.kill()`.

**Comment by ipetkov** [comment]
Thanks for the report @gralpli, this is a good catch, we should definitely update the docs there!

> Also: The killed child process remains as a zombie until the application is exited. This should at least be stated in the docs (better: the child should automatically be reaped).

We do put the child processes in a background queue and if the application continues to spawn and poll new child processes, they'll eventually get reaped. We don't discuss this in the docs strongly since we don't make a ton of guarantees when or if the reaping will happen (it's more of a best effort approximation to avoid lots of zombie processes).

> I'd also wish for a child_process.terminate() function in addition to child_process.kill().

This is effectively what calling `kill` used to do, but we received reports that it was possible for the applicaiton to block and get stuck when calling the kernel. What is the difference between `terminate` and `kill` that you are looking for?

**Comment by Darksonn** [comment]
This appears to still be the case. It would be nice to fix the documentation.

**Comment by ipetkov** [comment]
Also wanted to note that the `kill` method is now async and will perform the reaping of the child process, so this should be less of an issue going forward
