### ISSUE TITLE
Future types returned by AsyncReadExt methods are not public

### ISSUE THREAD

**Issue by crdumoul** [tokio-rs/tokio#2259]
## Version

0.2.11

## Platform

Linux packer-virtualbox-iso-1573705672 4.4.0-169-generic #198-Ubuntu SMP Tue Nov 12 10:38:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Description

Future types returned by AsyncReadExt methods (Read for the read method , ReadBuf for the read_buf method, ReadExact for the read_exact method, etc..) are not public. They should be public so they can be explicitly named in user code.

The reason I'd like these types to be public is so I can hold on to them and use them within other Future implementations. The specific example I'm trying to implement right now is a Future that progresses through a state machine where it does multiple read_exact calls on AsyncRead types.

**Comment by dekellum** [comment]
Some of the maintainers seem to consider it an advantage for Tokio not to include these types in its public interface, in that changes these types isn't a breaking change.  Personally I'm not sure there is much value to the privacy, in at least some of these cases where the type only exposes the `impl Future` interface anyway, but be forewarned.   

A workaround is to `Box<dyn Future<_>>` or `Pin<Box<dyn Future<_>>>`  the futures, at the cost of allocation and dynamic dispatch, which might not be significant in the greater performance picture with your application and `AsyncRead`/`Write`.

**Comment by taiki-e** [comment]
Closing in favor of #2723

**Comment by taiki-e** [comment]
Nah, it seems #2723 is only for non-`Future` types.

**Comment by AlexTMjugador** [comment]
Often it is possible to get named types from these methods by using a crate like `async-compat`, or the `compat` feature in `tokio-util`, to get the `futures-util` version of the Tokio `AsyncRead`, `AsyncWrite` or `AsyncSeek` traits. The `futures-util` implementation of the associated extension traits returns a public future, so that's a good way I can think of achieving this without doing boxing those Tokio opaque return types yourself.

However, this is pretty convoluted and ugly, and introduces layers of abstraction that definitely are not zero cost (heck, even `async-compat` can spawn a Tokio runtime to do its job with futures).

My use case for needing to know the return type of these `*Ext` traits is implementing an asynchronous spooled temporary file, and just relying on plain `poll_write` calls to roll it over to disk when the spooling buffer hits a size threshold gets pretty convoluted and messy quickly. But using these compatibility hacks is also messy. Is there any non-messy solution for this? If not, would it be fine for Tokio to just expose these return types and document that they may be subject to breaking changes? To be honest, I prefer having to update my code to a newer Tokio version than all this madness.

**Comment by barafael** [comment]
AFAICT, the `ReadBuf`-like types are all marked `pub` now. So maybe this can be closed.

**Comment by Darksonn** [comment]
The future types are still not public. But we will not expose them, since we want to replace them with `async fn` in the future, and not exposing them is most likely necessary for that.
