### ISSUE TITLE
Calling task::block_in_place within task::spawn_blocking panics with a failed assertion

### ISSUE THREAD

**Issue by overdrivenpotato** [tokio-rs/tokio#2327]
## Version

```
└── tokio v0.2.13
    └── tokio-macros v0.2.5
```

## Platform

`Darwin Markos-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

## Description

Calling `task::block_in_place` within a `task::spawn_blocking(...)` closure panics on a failed assertion.

Repro case:

```rust
use std::{thread, time::Duration};

#[tokio::main]
async fn main() {
    tokio::task::spawn_blocking(|| {
        tokio::task::block_in_place(|| {
            thread::sleep(Duration::from_millis(1000))
        });
    })
    .await
    .unwrap();
}
```

Output:

```
   Compiling test-threading v0.1.0 (/private/tmp/test-threading)
    Finished dev [unoptimized + debuginfo] target(s) in 1.59s
     Running `/Users/marko/.target-cargo/debug/test-threading`
thread 'tokio-runtime-worker' panicked at 'assertion failed: c.get()', /Users/marko/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/enter.rs:60:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', src/libcore/result.rs:1188:5
```

I expected `task::spawn_blocking` to be symmetric with `task::spawn` in this regard. It would be nice if this was the case as code using `block_in_place` would not have to worry about the caller context.

**Comment by jonhoo** [comment]
A similar example is
```
#[tokio::main]
async fn main() {
    tokio::spawn(async {
        tokio::task::block_in_place(|| {
            tokio::task::block_in_place(|| eprintln!("all good!"));
        });
    })
    .await
    .unwrap();
}
```
The user also can't work around this with `Handle::try_current().is_ok()` sadly, as this also crashes:
```rust
#[tokio::main]
async fn main() {
    tokio::spawn(async {
        tokio::task::block_in_place(|| {
            if tokio::runtime::Handle::try_current().is_ok() {
                tokio::task::block_in_place(|| eprintln!("all good!"));
            } else {
                eprintln!("still fine");
            }
        });
    })
    .await
    .unwrap();
}
```

**Comment by jonhoo** [comment]
So, after fixing that assertion failure, it turns out that these two cases are _slightly_ different. Specifically, in the `spawn_blocking` case, we basically have to choose whether running `block_in_place` when _not_ on the tokio runtime is a no-op or not. Currently, it panics with
> can call blocking only when running in a spawned task

This is intentional — it is so that we can tell users who try to `block_in_place` inside `block_on` (or on a non-threaded runtime) that that won't work. But tokio cannot distinguish between that case and the `spawn_blocking` case, since they both manifest as there being no currently active pool executor  (specifically, [`CURRENT`](https://github.com/tokio-rs/tokio/blob/8381dff39b845bc3b74c5e5c1c7ce78e39c34fe2/tokio/src/runtime/thread_pool/worker.rs#L194) is `None` in all those cases). If we were to enable `spawn_blocking` as a use-case, we would lose the error to users for the `block_on` and non-threaded runtime cases, which doesn't seem great.  The option we have is to introduce some additional state that lets that code realize that it is _specifically_ in the context of `block_on` or a _different_ runtime from the threaded one, and warn only in those cases. That would also mean that `block_in_place` is safe to use even when not on a tokio runtime, which would be pretty nice.

The nested `block_in_place` case is not as much of a problem, because we continue to be on an executor throughout, the executor core is just not there:
https://github.com/tokio-rs/tokio/blob/8381dff39b845bc3b74c5e5c1c7ce78e39c34fe2/tokio/src/runtime/thread_pool/worker.rs#L196

@carllerche would be good to get your input here.

**Comment by carllerche** [comment]
`block_in_place` *should* be made to work in more situations.

Off the top of my head, should work:

- `block_on`
- `spawn_blocking`

It should **not** work from within a `LocalSet` called from one of the above contexts.

**Comment by jonhoo** [comment]
@carllerche does `LocalSet` indicate somehow that it is the thing running a given task? So that we can check for that in `block_in_place`. Does `block_in_place` _currently_ work from within `LocalSet`?

**Comment by carllerche** [comment]
Currently, `block_in_place` **only** works from the work-stealing runtime. `LocalSet` cannot be moved into this runtime, so there is no interaction.

**Comment by jonhoo** [comment]
Sorry, what I mean is: what part of the code currently prevents it from being used inside `LocalSet`? Is `CURRENT` `None` there, or is it something else?

**Comment by jonhoo** [comment]
This will (in theory) be fixed by https://github.com/tokio-rs/tokio/pull/2410 :tada:
