### ISSUE TITLE
Tune task budget details

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2359]
This is a placeholder issue to track discussion related to the new automatic task yielding functionality.

Anyone should feel free to comment with their findings.

**Comment by driftluo** [comment]
For a similar resource-limiting usage scenario, I tried it once on yamux. This may cause the throughput to fall into an avalanche at some point. Later, I gave up this path. 

test case:

https://github.com/nervosnetwork/p2p/pull/213

I am more worried that this problem will reproduce under such a scheme.

**Comment by jonhoo** [comment]
@driftluo I don't _think_ that should quite apply here — this isn't limiting how many resources can be in use, nor does it limit parallelism. It only limits how much work can be done _per top-level task poll_. If there are no other ready tasks pending, then the task is run immediately again, and gets to resume its work.

**Comment by driftluo** [comment]
I read through the source code and understood the difference between the two.

Doing this at runtime can in some sense make resources more balanced, although it's not really a preemption. And a practice similar to what I did above, restricted within the Future, would result in a severe collapse effect.

If the task execution exceeds the limit, there may be some delay, but if the pressure is so great that all tasks are always ready, there is no problem with the current processing compared to the task response with only the number of workers, because in that situation, there's going to be problems no matter what you do.

**Comment by carllerche** [comment]
@driftluo A repro built on Tokio demonstrating the case would be helpful. We could look at optimizing it.

**Comment by khionu** [comment]
Being able to use a timeslice would be preferable for my use case. My Streams might run for several ms each iteration and others might run dozens of times in a single ms, but they should both get the same amount of CPU time before yielding. A configuration for this would be great.

**Comment by driftluo** [comment]
@carllerche I tested the effect of this use case under the current budget scenario and the impact was not significant, which I found acceptable

**Comment by carllerche** [comment]
I don't think we need this open anymore.
