### ISSUE TITLE
Ideas for v0.3

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2432]
A placeholder issue for ideas we have for 0.3 that have not yet been written up into proposals of their own.

* Deprecate `PollEvented` / `Registration`. These types expose a public dependency on `mio`. In the future, we may wish to provide `io_uring` support. Doing this would most likely require breaking away from a strict mio model.
* Rename `AsyncReadExt` and `AsyncWriteExt`.

**Comment by ipetkov** [comment]
One idea that @jonhoo and I were discussing is removing the `Future` impl on `process::Child` in favor of inherent `async fn wait(&mut self) -> ...` and `fn try_wait(&mut self) -> ...` methods which would better mirror `std`.

The borrow checker would prevent using both `wait` and `try_wait` at the same time which could cause confusion or potential lost wake ups. Although we could implement `wait` today in a backwards compatible manner, we should probably hold off on adding `try_wait` until we remove the `Future` impl

**Comment by ipetkov** [comment]
Another idea that would be interesting to explore is to move `signal` registration into the reactor itself (which would require opting in and enabling signal handling on runtime creation, which would be a breaking change).

The benefit there would be that we would only need to use one file descriptor *per reactor* (a strictly bounded amount), instead of the current one-file-descriptor-per-signal-listener

**Comment by asonix** [comment]
I hope however process::Child changes, that it becomes possible to send a kill signal to a process that is currently being waited on. Maybe a SignalHandle or something that has fallible methods for sending signals to child, that doesn't need mutable access to the child to work. If the child is already shut down, it simply returns an error when .kill() is called
