### ISSUE TITLE
zero-copy supports

### ISSUE THREAD

**Issue by Future2100** [tokio-rs/tokio#2438]
Is there possible to support zero-copy for the network socket?

**Comment by Darksonn** [comment]
Can you specify which copy you're asking if it is possible to avoid?

**Comment by Future2100** [comment]
@Darksonn  I want a zero-copy(such as Linux API splice) between two sockets.
Here is  a link reference: https://lwn.net/Articles/726917/

**Comment by Matthias247** [comment]
This isn't possible with the current set of APIs Tokio provides. These will copy all data to/from userspace buffers. Zero copy APIs are challenging, because they require the buffer to be alive for the whole duration of an async operation. However Rusts async tasks can be cancelled at any point in time.

There might be future support for this through io_uring APIs that people are thinking about, but this is currently only in the concept phase.

**Comment by DavidAntliff** [comment]
Consider a static buffer on Linux, provided by UIO or udmabuf - the buffer exists as contiguous physical memory. This buffer can be memory-mapped (`mmap`) and a userspace pointer provided to read/write to this buffer directly.

In C++ / ASIO, it's possible for the async socket `write()` to take this and perform zero-copy network transfer, taking data directly from the buffer. No copies are made. This achieves near the theoretical throughput of the network interface. I am hoping to port this application to Rust, and was considering using Tokio quite seriously.

Is this zero-copy from a fixed buffer possible to replicate in Tokio in any way at all? I understand that normally a userspace buffer would need to be moved around, but in this case it's literally a fixed buffer in physical memory, it does not move, and it's always available (essentially static).

If this isn't possible in Tokio, can anyone suggest a suitable alternative?

**Comment by Darksonn** [comment]
When you use Tokio's `write` method, it takes a `&[u8]` which can point into mmap'ed memory. It compiles down to a write syscall. If you need a different syscall, you can make the syscall manually with `try_io`.
