### ISSUE TITLE
Increase MAX_PAGES to prevent `reactor at max registered I/O resources` error in 32bit environment?

### ISSUE THREAD

**Issue by hatoo** [tokio-rs/tokio#2505]
Hi, I'm developing a HTTP load generator [oha](https://github.com/hatoo/oha) which uses tokio.

When I run `oha` in Raspberry pi 4B (raspbian 32bit) with a large number of concurrent connections (eg. -c 10000) I get the error `reactor at max registered I/O resources` which doesn't appear in other envrionments I have.

After some investigation, I've found that the error doesn't appear if `MAX_PAGES` is increased eg. `bit::pointer_width() as usize/3;`  .

https://github.com/tokio-rs/tokio/blob/8565a986018f4a442a7b71bba23c3b2f5de55604/tokio/src/util/slab/mod.rs#L38

I don't know what is the `MAX_PAGES` means but it solves my issue, so could you consider increase `MAX_PAGES` in 32bit environment?

thanks.

**Comment by hawkw** [comment]
For context: the IO reactor uses a slab structure to store data associated with I/O resources (such as sockets). Each IO resource is identified by a `usize`, which is used to index the slab. Storage for the slab is allocated in chunks which we refer to as "pages". The bits of the usize index identifying an IO resource  The `MAX_PAGES` constant limits the maximum number of pages, and is intended to reserve some of the bits in the word for identifying the thread ID that created the resource, and for a generation counter.

We currently limit `MAX_PAGES` to 1/4th of a word because the slab was originally implemented using a sharding scheme where each thread gets its own slab, and additional bits were needed to identify the thread ID. However, the sharding scheme is not currently used. This essentially means that we are artificially limiting the number of IO resources in the reactor.

On a 32-bit machine, 1/4th of a word is 8 bits, meaning the slab has 256 pages. On a 64-bit machine, the slab has 65356 pages. This means that in practice, it will be _extremely_ difficult for a 64-bit machine to concurrently register enough IO resources to meet the limit, while on a 32-bit machine, it seems like it can happen fairly easily under high concurrency — the problem you're seeing now. 

Because we aren't currently using the per-thread sharding scheme, I think we should just go ahead and increase `MAX_PAGES` to half a word. Since we're not storing thread IDs in the IO resource index, we're essentially wasting 8 bits of page index on 32-bit platforms and 16 bits on 64-bit platforms — Tokio doesn't currently use a largeish chunk of the `usize`. 8 more bits would probably be sufficient to make it very difficult for 32-bit platforms to exhaust the IO driver slab space.

If/when we re-implement the sharding scheme, we can decrease the max number of pages again to allow sharding, since sharding will distribute some IO resources across threads. However, in cases where a single task is responsible for accepting connections, it's certainly possible for one thread to be responsible for _most_ of the IO resources allocated. In that case, we probably don't want to turn `MAX_PAGES` back down to 1/4th of a word, at least not on 32-bit platforms. Instead, we probably want to use less than a quarter of the word for shard indices. I have some thoughts on how the sharding scheme can be used as a performance optimization without bounding the number of threads in the program, so it would be okay to lowball the number of shards. If memory serves, I think we are also being pretty generous about reserving additional bits for flags that we aren't currently using, and that should maybe be revisited as well.

**Comment by carllerche** [comment]
I'm going to punt this to 0.3 as 0.3 will include an overhaul of the IO system. This can be bundled in.
