### ISSUE TITLE
Support something like smol::Async

### ISSUE THREAD

**Issue by yihuang** [tokio-rs/tokio#2558]
https://github.com/stjepang/smol/blob/master/src/async_io.rs#L107

**Comment by Darksonn** [comment]
Tokio already has types such as [`TcpStream`][1] and [`UdpSocket`][2] that allows use of various types of sockets. Can you elaborate on what you feel that Tokio is missing?

For more low level access to the underlying IO loop, there's also [`PollEvented`][3].

[1]: https://docs.rs/tokio/0.2/tokio/net/struct.TcpStream.html
[2]: https://docs.rs/tokio/0.2/tokio/net/struct.UdpSocket.html
[3]: https://docs.rs/tokio/0.2/tokio/io/struct.PollEvented.html

**Comment by carllerche** [comment]
Closing as there is not enough information to support the request (use case, motivation, ....).

Feel free to comment if you disagree. I can reopen it.

**Comment by Darksonn** [comment]
The example you provided doesn't compile because [`zmq::Socket`][1] doesn't implement [`AsRawFd`][2]. Even if it did, making sockets return `WouldBlock` errors inside libraries that normally expect their sockets to be in blocking mode sounds like a recipe for disaster.

For example, if the operation required multiple writes to the underlying IO resource (which zmq's `send` definitely does), then returning an IO error in the middle would likely put the connection in an invalid state, and if you tried sending again, it would start over from the start of the message, even though some of the message was already sent.

[1]: https://docs.rs/zmq/0.9/zmq/struct.Socket.html
[2]: https://doc.rust-lang.org/stable/std/os/unix/io/trait.AsRawFd.html

**Comment by hawkw** [comment]
> And this is my experiment result with smol's `Async`: [erickt/rust-zmq@b33e08e](https://github.com/erickt/rust-zmq/commit/b33e08ed46dd111daf25878a757cd01c5e5558ac). You can see that it's trivial to integrate the existing zmq library into async world with this approach.

Does the linked code actually work? My understanding is that [`smol::Async::new`](https://docs.rs/smol/0.1.9/smol/struct.Async.html#method.new) requires the wrapped type implement the standard library's [`AsRawFd` trait](https://doc.rust-lang.org/nightly/std/os/unix/io/trait.AsRawFd.html), which (as far as I can tell) [`zmq::Socket` does not implement](https://docs.rs/zmq/0.9.2/zmq/struct.Socket.html#implementations). Am I missing something?

As a side note, `tokio` already provides [the `PollEvented` type](https://docs.rs/tokio/0.2.21/tokio/io/struct.PollEvented.html) for associating an I/O resource with the Tokio event loop. Using `PollEvented` in conjunction with [`mio`'s `EventedFd`](https://docs.rs/mio/0.6.22/mio/unix/struct.EventedFd.html) is similar to what `smol::Async` does (as I understand it). Would this work in your use-case?

**Comment by yihuang** [comment]
> > And this is my experiment result with smol's `Async`: [erickt/rust-zmq@b33e08e](https://github.com/erickt/rust-zmq/commit/b33e08ed46dd111daf25878a757cd01c5e5558ac). You can see that it's trivial to integrate the existing zmq library into async world with this approach.
> 
> Does the linked code actually work? My understanding is that [`smol::Async::new`](https://docs.rs/smol/0.1.9/smol/struct.Async.html#method.new) requires the wrapped type implement the standard library's [`AsRawFd` trait](https://doc.rust-lang.org/nightly/std/os/unix/io/trait.AsRawFd.html), which (as far as I can tell) [`zmq::Socket` does not implement](https://docs.rs/zmq/0.9.2/zmq/struct.Socket.html#implementations). Am I missing something?

The `AsRawFd` is implemented in predecessor commit in the same [PR](https://github.com/erickt/rust-zmq/pull/306).

> 
> As a side note, `tokio` already provides [the `PollEvented` type](https://docs.rs/tokio/0.2.21/tokio/io/struct.PollEvented.html) for associating an I/O resource with the Tokio event loop. Using `PollEvented` in conjunction with [`mio`'s `EventedFd`](https://docs.rs/mio/0.6.22/mio/unix/struct.EventedFd.html) is similar to what `smol::Async` does (as I understand it). Would this work in your use-case?

Thanks, I'll try this, maybe it'll come out similar.

**Comment by yihuang** [comment]
> The example you provided doesn't compile because [`zmq::Socket`](https://docs.rs/zmq/0.9/zmq/struct.Socket.html) doesn't implement [`AsRawFd`](https://doc.rust-lang.org/stable/std/os/unix/io/trait.AsRawFd.html). Even if it did, making sockets return `WouldBlock` errors inside libraries that normally expect their sockets to be in blocking mode sounds like a recipe for disaster.
> 
> For example, if the operation required multiple writes to the underlying IO resource (which zmq's `send` definitely does), then returning an IO error in the middle would likely put the connection in an invalid state, and if you tried sending again, it would start over from the start of the message, even though some of the message was already sent.

The AsRawFd is implemented in predecessor commit in the same [PR](https://github.com/erickt/rust-zmq/pull/306).

I think the zmq API is designed to work with both blocking and non-blocking style.
[DONTWAIT](https://docs.rs/zmq/0.9.2/zmq/static.DONTWAIT.html)
[get_fd](https://docs.rs/zmq/0.9.2/zmq/struct.Socket.html#method.get_fd)

- First of all, from my understanding, what the `get_fd` returns is not the actual communication socket, but an event notification fd.
- What the `send` does is actually put the message into a queue, it only blocks if the queue is full.

**Comment by Darksonn** [comment]
Interesting. I would still be super worried about the Rust shim around the C library doing the right thing. But yes, `PollEvented` would be the tool here.

**Comment by yihuang** [comment]
> Interesting. I would still be super worried about the Rust shim around the C library doing the right thing. But yes, `PollEvented` would be the tool here.

I did a little bit more research on this, find [this](https://github.com/zeromq/libzmq/issues/3641#issuecomment-524656929), which is summarised by one of the authors of [tmq](https://github.com/cetra3/tmq), which is a "Rust ZeroMQ bindings for Tokio", it looks decent written, and uses the `PollEvented<EventedFd>` under the hood. So I guess the problem is solved for me ;D

**Comment by hawkw** [comment]
Maybe something we can do on Tokio's side to help prevent similar confusion in the future is highlighting the use of `PollEvented` to add new evented primitives to Tokio's event loop more clearly in the documentation?

**Comment by yihuang** [comment]
> Maybe something we can do on Tokio's side to help prevent similar confusion in the future is highlighting the use of `PollEvented` to add new evented primitives to Tokio's event loop more clearly in the documentation?

I just implemented the `Async` on top of `PollEvented` and `mio::EventedFd`, [tokio-async-io](https://github.com/yihuang/tokio-async-io).
The example with rust-zmq runs ok, I guess the correctness still needs some review from experts.
Particularly, I don't understand why [this code](https://github.com/yihuang/tokio-async-io/blob/6e420b1fd90e7651f6e4c3fd6109f6ddfc5e1ba3/src/lib.rs#L68) is necessary. @stjepang

**Comment by WGH-** [comment]
> Maybe something we can do on Tokio's side to help prevent similar confusion in the future is highlighting the use of `PollEvented` to add new evented primitives to Tokio's event loop more clearly in the documentation?

Is there a easy way to wrap an existing non-blocking FD to provide `AsyncRead`, though? Well, of course one just copy-paste some code from there - https://github.com/tokio-rs/tokio/blob/4c4699be00bf4aee6218f84ec606e043286a8c2a/tokio/src/process/unix/mod.rs#L140-L231 - but that's no fun.

**Comment by Darksonn** [comment]
@WGH- The `mio` crate has several implementations of the `Evented` trait, which can be used directly in `PollEvented`.

**Comment by WGH-** [comment]
@Darksonn are you referring to `EventedFd`? Although it provides quite a bit of value, you still need to implement `io::Write`/`io::Read` manually (like the linked fragment from tokio's process does), which is somewhat considerable amount of boilerplate.

Doing something like `let f: tokio::fs::File = unsafe { std::fs::file::frow_raw_fd(fd) }.into();` could work, however, `tokio::fs::File` doesn't handle `WouldBlock`, returning it to the caller instead of waiting. For example, Go fixed this awhile ago: https://github.com/golang/go/commit/ea5825b0b64e1a017a76eac0ad734e11ff557c8e (there's a typo in commit title, but the description is accurate)

**Comment by Darksonn** [comment]
Well converting it to a `File` is a bad idea, as files are incompatible with APIs such as epoll and use blocking IO on a separate threadpool. You would have to convert it to e.g. a `TcpStream` to get something that actually ties it in with epoll.

In any case, we are currently working on Tokio v0.3, which will rework this part of the API to remove the public dependency on mio. Designing this part of the API is still a work-in-progress.

**Comment by WGH-** [comment]
FWIW, the FD in question is anonymous pipe. Unfortunately, the `std::process` (and `tokio::process`) doesn't have an easy way to pipe stdout and stderr into a single stream (a la `2>&1`), so the only option is to create a pipe manually, and pass its write end as both stdout and stderr. This is the easy part. Wrapping the other end of the pipe into something nonblocking and tokio-compatible is the hard part (requires writing the boilerplate). See also https://github.com/rust-lang/rfcs/issues/871

Although pipes are probably the main thing here, I believe this problem is not limited to pipes. There's quite a few of Linux-specific whateverfd APIs that are 1) pollable 2) provide read/write interface (eventfd, timerfd), and it would be cool if one could use them with Tokio without writing extra code.

**Comment by tobz** [comment]
These are likely best written as utilities or utility crates, so that Tokio doesn't have to be coupled to specific Linux-only subsystems, etc.  We've traditionally shied away from maintaining OS-specific facilities because it adds to the support/testing burden.

Personally, writing <20 lines of code for `Evented` seems like a very low bar if someone needs it.  I'm not sure why `tokio-process` does it the way that it does, but the normal case absolutely doesn't involve writing `Read`/`Write` implementations, as seen in the examples here: https://docs.rs/mio/0.6.22/mio/unix/struct.EventedFd.html#examples

**Comment by WGH-** [comment]
https://docs.rs/tokio/0.2.22/tokio/io/trait.AsyncRead.html#impl-AsyncRead-11
```
impl<E> AsyncRead for PollEvented<E> where
    E: Evented + Read + Unpin, 
```

If you want to read from that file descriptor using `AsyncRead`/`AsyncReadExt`, plain `EventedFd` is not sufficient, because it doesn't provide `Read` on its own. You need to wrap it with something that provides it, and that exactly what `tokio/tokio/src/process/unix/mod.rs` does.

**Comment by tobz** [comment]
Ah, you're right.  I was looking at some similar code I had written that only used `Evented` for readiness, not actual reading/writing.

At any rate, everything else I said still stands. :P

**Comment by WGH-** [comment]
Hmm, given that tokio 0.3 has `tokio::io::unix::AsyncFd` now, I suppose this issue was silently addressed?

**Comment by Darksonn** [comment]
The situation has changed since we are moving away from having mio in the public API, yes. It is still not equivalent to smol's Async type.

**Comment by WGH-** [comment]
True, but the amount of boilerplate code required to wrap with `AsyncFd` and add required operations is much smaller than before.

**Comment by Darksonn** [comment]
I am happy to hear you like the new API :)
