### ISSUE TITLE
calling futures::executor::block_on in block_in_place may hang

### ISSUE THREAD

**Issue by leoyvens** [tokio-rs/tokio#2603]
**Version**
0.2.21

**Platform**
Linux

**Description**
I'm basically having the problem in this issue https://github.com/tokio-rs/tokio/issues/2376, which is to use `block_on` within a tokio task, and sometimes it hangs. This comment https://github.com/tokio-rs/tokio/issues/2376#issuecomment-608959390 says using `spawn_blocking` fixes it. I figured `block_in_place` should also work, but it didn't. A guess for why is that when using `block_in_place` the thread local variable for the task budget continues to decrease, when it should stop counting. Possibly as [was done for LocalSet](https://github.com/tokio-rs/tokio/pull/2462).

**Comment by nlfiedler** [comment]
If the code in question is deeper in the call stack, what should I do? Calling `futures::executor::block_on()` just _happens_ to work, but that sounds risky given the comments here and the related issue.

I've got a small crate inside a larger application, and that larger application is using actix-web (and hence tokio) to serve web and GraphQL content. This smaller crate is thoroughly synchronous. It is one of several similar crates, so changing everything to asynchronous is a big change. This small crate is calling a library function that returns a `Future` that I need to do something with in the of middle my synchronous function so I can return a result. How do I wait on this future without writing my own executor?

I'm sure this is a stupid question, and I apologize for that. I've spent several hours reading documentation and trying everything I could think of, short of hand-rolling my own executor. Should I give up and change the entire application to be asynchronous everywhere so I can call this one function?

Thanks for tokio by the way, the docs are well written and the API is rather extensive.

**Comment by Darksonn** [comment]
@nlfiedler You should make use of the fact that calling [`Handle::block_on`][2] inside calls to [`spawn_blocking`][1] is perfectly okay. The `spawn_blocking` function has to be called in async code, so you should add it at your outer transition from async to sync code.

I recommend using our `Handle::block_on` instead of the `block_on` from futures. Any code running inside `spawn_blocking` is in Tokio's context, so you can simply ask for a handle when you need it with [`Handle::current`][3]. 

Note that if your synchronous code does anything else blocking such as using std IO types, then you must use `spawn_blocking` for that reason too.

[1]: https://docs.rs/tokio/0.2/tokio/task/fn.spawn_blocking.html
[2]: https://docs.rs/tokio/0.2/tokio/runtime/struct.Handle.html#method.block_on
[3]: https://docs.rs/tokio/0.2/tokio/runtime/struct.Handle.html#method.current

**Comment by nlfiedler** [comment]
Thank you for the explanation, that confirms what I was afraid of. This application started two years ago, long before async/await was stabilized. The async aspects of the application consist of the `#[actix_rt::main]` on the main function (which I believe is equivalent to `#[tokio::main]`), and the `Future` that is now coming back from the library (rusoto), which was a recent change in their API. I'm stuck between a rock and a hard place, looking for an escape hatch, even if only temporarily.

**Comment by Darksonn** [comment]
You could consider using [`block_in_place`][1] as an escape hatch, but I generally do not recommend it as there are several situations where it doesn't work (e.g. single-threaded executor and the `main` function).

[1]: https://docs.rs/tokio/0.2/tokio/task/fn.block_in_place.html

**Comment by nlfiedler** [comment]
Yes, I saw that, and it is helpful for a situation other than mine. I need to realize the results of the `Future` from code that is synchronous, deep within the call stack of a thread managed by tokio.

Anyway, I've derailed this issue long enough. Thanks for your help.

**Comment by Darksonn** [comment]
You can use `block_in_place` for that. You simply put a `block_on` inside it.

**Comment by nlfiedler** [comment]
Yep, tried that -- you get "runtime inside a runtime" error.

**Comment by carllerche** [comment]
Try again w/ the latest release? https://github.com/tokio-rs/tokio/pull/2711 might have fixed it.
