### ISSUE TITLE
Allow any error type for `tokio::io::stream_reader`

### ISSUE THREAD

**Issue by jhpratt** [tokio-rs/tokio#2640]
**Is your feature request related to a problem? Please describe.**
I am trying to asynchronously read the bytes returned from an HTTP request. 

```rust
let url = "http://example.com";
let bytes = reqwest::get(url).await?.bytes_stream();
let bytes = tokio::io::stream_reader(bytes);
```

**Describe the solution you'd like**
Relax the constraint requiring a `std::io::Error`. It looks like the error type is passed through to `AsyncRead` and `AsyncBufRead`. As such, an additional type parameter (defaulting to `std::io::Error` for back-compatibility) would be ideal, as it would allow any error type.

**Describe alternatives you've considered**
Aside from duplicating the code locally with the change, I've no idea what alternatives there even could be.

**Comment by Darksonn** [comment]
Since the `StreamReader` must forward the error through the [`AsyncRead`][2] / [`AsyncBufRead`][3] traits, it must be able to convert it to an io error, as those traits require an io error. We could relax it to accept any error that implements `Into<io::Error>`, but that does not solve your problem as [`reqwest::Error`][1] does not implement that trait.

[1]: https://docs.rs/reqwest/0.10/reqwest/struct.Error.html
[2]: https://docs.rs/tokio/0.2/tokio/io/trait.AsyncRead.html
[3]: https://docs.rs/tokio/0.2/tokio/io/trait.AsyncBufRead.html

Another option is to use [`StreamExt::map`][4] to change the error type of a stream. For an error that is convertible to an io error directly, you can do this:
```rust
use tokio::stream::StreamExt;

let bytes = tokio::io::stream_reader(bytes.map(|res| Ok(res?)));
```

[4]: https://docs.rs/tokio/0.2/tokio/stream/trait.StreamExt.html#method.map

However for errors that are not convertible using the question mark (such as reqwest's error), you have to do something like this:
```rust
fn map_reqwest_error(error: reqwest::Error) -> std::io::Error {
    ...
}

use tokio::stream::StreamExt;

let url = "http://example.com";
let bytes = reqwest::get(url).await?.bytes_stream();
let bytes = tokio::io::stream_reader(bytes.map(|res| res.map_err(map_reqwest_error)));
```

Note that the equivalent api in the hyper crate, which the `stream_reader` utility was partly created for, uses an IO error, and as such can be used directly.

**Comment by jhpratt** [comment]
Ah, I didn't check to see that `AsyncRead` and `AsyncBufRead` _required_ an `io::Error`. At least for my purpose, mapping the `reqwest::Error` to `io::Error` using `ErrorKind::Other` should suffice.

Closing as this would likely only be actionable on a per-crate basis.
