### ISSUE TITLE
tokio::process::Command leaves zombies when child future is dropped

### ISSUE THREAD

**Issue by flumm** [tokio-rs/tokio#2685]
**Version**

```
└── tokio v0.2.22
    └── tokio-macros v0.2.5
```

**Platform**
Linux zita 5.4.44-2-pve #1 SMP PVE 5.4.44-2 (Wed, 01 Jul 2020 16:37:57 +0200) x86_64 GNU/Linux

**Description**
when i start a child process with 'kill_on_drop(true)'
and before the future is finished i drop it, there is a zombie
left until a new Child future is polled.

short reproducer: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6746973d696b5122bc212e4bf6436092

i commented out the stdin code for the playground
when run locally it is easier to see that there is a defunct process when looking at e.g., 'ps ax | grep sleep' output
as long as no new child future is polled

i would expect that someone (e.g. the drop handler?) polls the future once again
so that the reaper can call waitpid once more...

**Comment by davidbarsky** [comment]
Does this playground show the behavior that you're expecting? https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2fb1919dae4c46a305d328cb333cd79c

You might need to `.await` the task you spawn.

**Comment by flumm** [comment]
No actually the problem is that after the child in the first task is dropped, the child process is killed but waitpid is never called for the first spawned child. Only when there is another command spawned and its future is polled, waitpid is called again

You can verify this by removing the second command spawning an waiting eg. on an input. You can now see that the child process is a zombie

**Comment by ipetkov** [comment]
Hi @flumm thanks for the report! It is is a known limitation that we do not call `waitpid` on drop since we found in the past that there is no guarantee the kernel will not block even immediately after `sigkill` is sent to the child: alexcrichton/tokio-process#51

Tokio will [perform a *best-effort* attempt to clean up zombie processes](https://github.com/tokio-rs/tokio/blob/8a7e57786a5dca139f5b4261685e22991ded0859/tokio/src/process/unix/reap.rs#L102); if no more processes are spawned via tokio, then it is possible some of the processes remain as zombies.

One possible work around is to avoid dropping `child` structs and await them to completion.

**Comment by flumm** [comment]
hmm... ok so this is 'known' behaviour
i would argue though that it makes the 'kill_on_drop' feature a little hard to use, since it will often
leave zombies in long running applications that are not guaranteed to spawn another process
(since there is no way to await a dropped future)

it probably would be good to somehow extract a handle to to kill it, like mentioned in #2512 
but the solution there with tokio::select is probably good enough for us now

**Comment by ipetkov** [comment]
Docs around this have been updated in #2952 and we've revamped the orphan reaping implementation in #2907 so hopefully this should be less of a problem now. Going to close this out, but feel free to reopen if there are other questions!
