### ISSUE TITLE
Consider coordinating with a Mio 0.7 release

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#27]
The [Mio 0.7 milestone](https://github.com/carllerche/mio/milestone/7) represents the known breaking changes that have been queued up.

This issue relates to #33 as maintaining a single global event loop across breaking Tokio releases requires the Mio version to remain constant.

**Comment by aturon** [comment]
I don't think that we should block 0.1 on a coordinated breaking change. If we are going to bump major versions in mio or tokio-io, that essentially means bumping across the whole stack, which in turn is going to lead to another batch of API re-evaluation etc, to take maximal advantage of the bump.

To be clear, I'm not against bumping the stack at some point. **But I'm strongly opposed to blocking 0.1 of this crate on it**:

- We've put a lot of work into the design as a backwards-compatible change, and building consensus around it with the RFC. Modulo agreement on the implementation details, it's something we could ship in the very near future, enabling an **incremental step** in Tokio's evolution, rather than tying everything to a single "big bang".

- In particular, by shipping *now*, and planning on a 0.2 *later*, we'll have the ability in the 0.2 release to address any problems with this crate's design in the meantime. If we tie them together, we're banking on getting this crate's design right on the first shot (since an 0.3 would probably not come for some time.) This is what I mean by finding ways to ship incrementally; we can gather more feedback sooner, and generally move the ecosystem in a positive direction in smaller steps.

- A major version bump is by nature going to be a protracted affair; we'd want to revisit issues in the futures crate, and hence relitigate arguments about some basic aspects there. Since there's some impetus to eventually incorporate futures into `libcore` (to support first-class async/await), there'd be significant pressure to try to "get it right". Similar pressures apply elsewhere. Now, this is all worthwhile work, but there's no question in my mind that it'd *significantly* push back our current efforts, which have already been progressing very slowly as-is. There's no way we could ship in 2017.

- There's been some concern that publishing this crate, then doing a 0.2 bump across the board shortly thereafter would not be a good experience for the ecosystem. I agree with that sentiment, but as above, believe that a 0.2 bump is going to require enough lead time that this is not a realistic concern.

I'd propose we work to ship this crate ASAP, and then *immediately* begin assessment and planning around a 0.2 of the stack. By the time we've fully re-evaluated the other crates, we'll likely also have some real-world feedback on this one that we can also incorporate.

**Comment by carllerche** [comment]
I believe that the current plan is to only release `tokio` 0.1 and then coordinate an ecosystem bump after that.
