### ISSUE TITLE
Figure out plans for UdpFramed

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#2830]
The `UdpFramed` type in `tokio-util` was disabled https://github.com/tokio-rs/tokio/pull/2828, because the implementation depended on `poll_send_to` and `poll_recv_from` methods, which were removed. We need to figure out what do with this type going forward. Some options:

- Completely remove `UdpFramed`.
- Add back undocumented `poll_send_to` and `poll_recv_from` methods that behave similar to `AsyncRead` and `AsyncWrite` internally.

**Comment by leshow** [comment]
Chiming in as a user of `UdpFramed`. I wasn't aware that the `poll_` fns were removed from `UdpSocket`, is there still a way to call recv from a `Poll` returning fn? I guess one could still call `recv_from(..).poll_unpin(cx)` ? 

One unfortunate thing about `UdpFramed` is that it ceases to work if you `split()` a `UdpSocket` since it requires a concrete type that won't accept a `RecvHalf`. I realize the docs for `UdpFramed` points to calling `split` after the fact, but AFAIK this is the `split()` from the futures_util library, not tokio, which uses their `BiLock`, whereas the `UdpSocket::split` just creates an `Arc`.

In any case I think `UdpFramed` has some value, would be nice if it were generic though. 

Am I correct in thinking that if it were removed there would be no real 'recommended path' for getting from a `UdpSocket` to a `Stream`? Especially with the removal of the aforementioned `poll_` methods?

**Comment by carllerche** [comment]
IIRC, the conclusion is to expose` poll_*` functions in `tokio` and to commit to supporting them in 1.0.

**Comment by carllerche** [comment]
The remaining 0.3 steps are tracked in #2928. I am removing the 0.3 milestone from this issue but leaving it open. We still need to bring back `UdpFramed`.

**Comment by leshow** [comment]
Would you like to bring it back more or less like it was before, just updated to work with the new apis? Which is to say, concurrent send/recv should be pretty simple. I can submit a PR for something like this if you want.

**Comment by Darksonn** [comment]
@leshow You would have to add `poll_*` functions to `UdpSocket` to make it possible to implement, but yes.

**Comment by MagicRB** [comment]
I really need this struct, please don't take this as me being impatient, but I can't update the version of tokio I use. I need to create a stream from a UdpSocket so that I can use it in actix, is there some kind of temporary hack I use until this gets resolved?

**Comment by leshow** [comment]
@MarkusJais  I got a comment in my email asking about what you can do without `UdpFramed` if you want to make a `Stream`. I just wanted to add that now that `poll_` methods are back in tokio 3.2, `UdpFramed` isn't the *only* way to get a `Stream`. You can simply implement `Stream` yourself for a type, that's an option.

If you don't want a `Stream` impl specifically, but just want to turn a `UdpSocket` into a bunch of frames, there's nothing stopping you from wrapping `UdpSocket` in another type and adding a `async fn` method to decode a frame, then calling that in some kind of a loop.

Of course, the PR to add `UdpFramed` is just waiting to be merged, so you can totally just wait for the next release too.

**Comment by MagicRB** [comment]
Yeah, I wrote that commend, then I realized there already is a PR so I deleted it, sorry for the trouble

**Comment by tbraun96** [comment]
``UdpFramed`` should definitely be added. Crates I'm upgrading depend on it. For now, having to use a thin wrapper

**Comment by leshow** [comment]
`UdpFramed` is added and has been merged, this issue can probably be closed?

**Comment by Darksonn** [comment]
Yeah, it is available as [`tokio_util::udp::UdpFramed`][1] in the latest version of tokio-util. Closing.

[1]: https://docs.rs/tokio-util/0.5/tokio_util/udp/struct.UdpFramed.html
