### ISSUE TITLE
implement TryFrom so that std::process:ChildStdxx can be converted to tokio::process:ChildStdxx

### ISSUE THREAD

**Issue by wangbj** [tokio-rs/tokio#2837]
**Is your feature request related to a problem? Please describe.**
Both `std` and `tokio` have `Stdin`/`Stdout`/`Stderr` type, IMO `tokio` ones are more powerful because they implements `AsyncRead`. 

In *tokio/src/process/unix/mod.rs*, tokio's `Stdxx` are wrappers around `std::process::Stdxx`:

```
pub(crate) type ChildStdin = PollEvented<Fd<std::process::ChildStdin>>;
pub(crate) type ChildStdout = PollEvented<Fd<std::process::ChildStdout>>;
pub(crate) type ChildStderr = PollEvented<Fd<std::process::ChildStderr>>;
```

So it should be really easy to add `impl TryFrom<std::process::ChildStdin> for ChildStdin` for example, not to mention tokio has function like `fn stdio<T>(option: Option<T>) -> io::Result<Option<PollEvented<Fd<T>>>>`.

**Describe the solution you'd like**
Add `impl` `From` or `TryFrom` so that it is possible to convert `std::process::Stdxx` into `tokio::process::Stdxx`.

**Additional context**
Right now it is impossible (from external API) to construct `tokio::process::Stdxx` without `execve` (via `Command`). it would be valuable to construct them with `nix::unistd::fork`. Since `std::process::Stdxx` is just a thin-wrapper around `FileDesc`, thanks to rust's zero cost abstraction, they're identical to `c_int` (32-bit, or *HANDLE*/64-bit on Windows). But this is not true for `tokio::process::Stdxx`, if we can convert `std::process::Stdxx` into `tokio::process::Stdxx`, then we can do IO redirections with `unistd::fork`.

**Comment by Darksonn** [comment]
This seems reasonable to me.

**Comment by ipetkov** [comment]
IMO there isn't a ton of value in converting an `std::ChildStd{in, out, err}` to a `tokio` equivalent in the same sense that there isn't a ton of value in converting a raw file descriptor into an `std::ChildStd{in, out, err}`, since the latter delegates to the former.

The more *interesting* feature ask here, in my opinion, would be to **support ergonomically converting any raw file descriptor equivalent into something that is `Async{Read, Write}`**.

Doing so today isn't "hard", but it does require knowing about `mio`'s `Evented` type, making a wrapper around the file descriptor, delegating read/write impls, making the descriptor non-blocking, and passing it into `PollEvented` (after all, this is what tokio does for the child stdio handles); it would be good to avoid all this boilerplate in general rather than *just* solving it for the process handles.

I know that our plans for 0.3 involve hiding `mio` from the public interfaces (with a migration to `mio` 0.7 to boot). Maybe there are already planned utilities for this, but we should have some sort of api that takes any `T: IntoRawFd` and converts it to some `PollEvented` equivalent

**Comment by wangbj** [comment]
> The more interesting feature ask here, in my opinion, would be to support ergonomically converting any raw file descriptor equivalent into something that is Async{Read, Write}.

Agreed, I'm already using mio (0.6 because tokio 0.2 depends on it), would this be reasonable feature to add?

**Comment by Darksonn** [comment]
In my opinion, both make sense.

**Comment by ipetkov** [comment]
Relevant #2728 and #2903
