### ISSUE TITLE
FR: async spawn_blocking

### ISSUE THREAD

**Issue by fenollp** [tokio-rs/tokio#2866]
**Is your feature request related to a problem? Please describe.**
There's this app I'm writing which needs a couple background threads for, for instance, receiving from a gRPC stream and paint UI accordingly. This work already uses `async` functions so I'd like to be able to spawn blocking async code.
Today I can't use async code with `spawn_blocking`:
> expected an `FnOnce<()>` closure, found `impl futures::Future`

**Describe the solution you'd like**
I'd rather use a version of `tokio::task::spawn_blocking` that directly takes an async f, potentially only allowing `()` as return value.
```rust
	// ...
    tokio::task::spawn_blocking_async(async move {
        loop_recv(appref, ch2, ctx2).await; // My async code
    });
	// ...
```

**Describe alternatives you've considered**
The only way I have found to achieve what I want is:
```rust
	// ...
    tokio::task::spawn_blocking(move || {
        let rt_handle = tokio::runtime::Handle::current();
        rt_handle.block_on(async move {
            loop_recv(appref, ch2, ctx2).await; // My async code
        });
    });
	// ...
```
Is this is the best I can do today? Am I doing something wrong here?

I've tried opening a PR but can't get something to compile. What I have:
```rust
pub(crate) fn spawn_blocking_async<F>(f: F) -> JoinHandle<F::Output>
where
    F: Future + Send + 'static,
    F::Output: Send + 'static,
{
    let rt = context::current().expect("not currently running on the Tokio runtime.");

    let (task, handle) = task::joinable(BlockingTask::new(move || {
        let rt_handle = crate::runtime::Handle::current();
        rt_handle.block_on(async move {
            f.await
        });
    }));
    let _ = rt.blocking_spawner.spawn(task, &rt);
    handle
}
```

**Additional context**
I was a bit surprised that `tokio::spawn(async move { ... });` had no blocking equivalent and surely some other people are/will be too. Maybe this is a fair addition.

**Comment by Darksonn** [comment]
There's no async version of `spawn_blocking` because you generally shouldn't run blocking things in async code.

**Comment by fenollp** [comment]
Thanks for your answer!
I understand there is Rust today does not provide the means for a preemptive scheduler of async tasks. And that is precisely why I have to signal to the executor that this loop has to run in a dedicated thread (thus `spawn_blocking`), otherwise this loop monopolizes execution resources (even with `yield_now`).
I hope this makes it clearer why a `spawn_blocking` for async code makes sense here. Again I'd like this to be provided by the lib as a means of signaling while also making sure it's implementation is correct.

**Comment by Darksonn** [comment]
If you really really want to run blocking things in async code, you can indeed combine `spawn_blocking` and `block_on`.
```rust
tokio::task::spawn_blocking(move || {
    Handle::current().block_on(async move {
        ...
    })
});
```
I do not think it makes sense to add such a utility function to Tokio. Generally you are supposed to factor the blocking parts into sync code and run that directly in `spawn_blocking` rather than doing what I described above.

**Comment by fenollp** [comment]
Thanks for showing the correct way of doing this. 

Could you explain why only sync code should generally be ran under spawn_blocking? Are there technical reasons?

Thanks

**Comment by Darksonn** [comment]
Generally the reason you use async/await is so that you can swap the current task on a thread repeatedly to do many things on a single thread. That's the point of async/await. If you block in an async task, this is no longer possible. Of course, if there is only one task on the thread, then it's not an issue that you aren't letting other tasks run, but then it doesn't really make sense to use async/await. It doesn't give you anything new compared to sync code.

Additionally, I think having such an API would be confusing to new users of Tokio, while not gaining much to those that want to do it anyway. It's important to introduce a clear distinction between async and blocking code.
