### ISSUE TITLE
net: provide a TcpSocket type to enable basic socket configuration

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2902]
Currently, there is no easy way to configure a TCP socket before connecting or listening. Crates such as `net2` and `socket2` allow configuring sockets, but this adds a lot of friction to perform basic configuration and then establish an asynchronous connection.

To remedy this, Tokio can provide a `TcpSocket` type. This would provide a hook point to configure the socket.

```rust
struct TcpSocket { ... }

impl TcpSocket {
  pub fn new_v4() -> TcpSocket;

  pub fn new_v6() -> TcpSocket;

  pub async fn connect(self, addr: SocketAddr) -> TcpStream;

  pub fn listen(self, addr: SocketAddr) -> TcpListener;
}
```

We could provide fns to set common options. We could also implement `AsRawFd` which would enable the caller access to the full gamut of configuration.

**Comment by sfackler** [comment]
Any reason to limit this to TCP rather than arbitrary socket types like the socket2 crate does?

**Comment by carllerche** [comment]
@sfackler I think we can add other flavors as needed. The intent is not to be a comprehensive builder API but to handle common cases + be able to drop to `socket2` easier.

Using `socket2` is not super straightforward and I think part of that is it tries to cover *all* cases.

**Comment by iximeow** [comment]
I actually ran into this just this week trying to configure the backlog for a `UnixListener`. Personally a doc comment on `tokio::net::UnixListener` (or `TcpListener` or ...) pointing me towards `socket2` and `from_std` would have been most helpful. _Once I'd found it_, using `socket2` was pretty straightforward...

Perhaps it could make sense for `TcpStream`/`TcpListener` and friends to have a `fn from_socket2(s: socket2::Socket)` that bridges with the appropriate `TcpListener::from_std(s.into_tcp_listener())`-type conversion? That's more symmetric, tokio-wise, across different domains. Admittedly just taking any ol `socket2::Socket` might mean taking an ipv4 socket to construct a `UnixStream` and I don't know in what fascinating way that might explode.

At the very least it seems it'd be an error to do:
```rust
TcpSocket::new_v6().connect("127.0.0.1:8080".parse().unwrap())
```
since `addr` can indicate v4/v6-ness for IP connections. Might be better to just take a `SocketAddr` in a `new()`, and infer IP version thre rather than later on?

**Comment by carllerche** [comment]
Depends on https://github.com/tokio-rs/mio/pull/1358
