### ISSUE TITLE
meta: release Tokio 0.3

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2959]
Tracking the 0.3 release.

* [x] Blog post
* [x] Changelog

**Comment by MCOfficer** [comment]
I'm not sure if I missed any such discussion, but can you explain why this was tagged `v0.3.0` instead of `v1.0.0-beta1`?

Quoting the changelog (emphasis mine):

> This represents a 1.0 beta release. APIs are polished and future-proofed. **APIs not included for 1.0 stabilization have been removed.**


I know that *technically* `0.*` releases are not really bound by the semver rules (any change can be breaking), but i don't see why one wouldn't use use a `1.0.0-beta*` instead.

**Comment by Darksonn** [comment]
It's because `1.0.0-beta*` works rather poorly with cargo, which is not able to figure out that later beta releases are semver compatible with earlier ones. On the other hand, cargo understands 0.3.x quite well semver-wise.

Regarding "any change can be breaking", that's not really the convention used by Rust libraries. All 0.3.x releases should be semver compatible when x is increased, and similarly for 0.2.x.

**Comment by Darksonn** [comment]
Closing this because 0.3.0 has been released.

**Comment by MCOfficer** [comment]
> It's because `1.0.0-beta*` works rather poorly with cargo, which is not able to figure out that later beta releases are semver compatible with earlier ones. On the other hand, cargo understands 0.3.x quite well semver-wise.
> 
> Regarding "any change can be breaking", that's not really the convention used by Rust libraries. All 0.3.x releases should be semver compatible when x is increased, and similarly for 0.2.x.

Fair enough. I just stumbled over 0.3 being a breaking change compared to 0.2, but i suppose that can't be helped.

**Comment by Darksonn** [comment]
Yes, pre-1.0 we consider 0.x changes breaking, but not 0.x.y changes. Cargo handles this correctly.
