### ISSUE TITLE
0.2 read_buf() to 0.3 read() migration results in invalid behavior

### ISSUE THREAD

**Issue by krojew** [tokio-rs/tokio#2976]
**Version**
tokio v0.3.0
tokio-macros v0.3.0

**Platform**
Linux Desktop 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description**
After migrating from tokio 0.2 to 0.3 and changing `read_buf()` call to `read()` on `tokio::net::tcp::OwnedReadHalf`, the returned bytes read is always 0, when the exact same connection using `read_buf()` actually reads data.

The issue is 100% reproducible by running tests for https://github.com/krojew/rust-zookeeper/tree/tokio-0.3.

**Comment by Darksonn** [comment]
I assume you are referring to this:
```rust
let mut buf = BytesMut::with_capacity(4096);
while let Ok(read) = rx.read(&mut buf).await {
```
What happens here is that [`AsyncReadExt::read`][1] takes an `&mut [u8]`, so the `&mut BytesMut` is coerced to a slice of the data already in it, but since you just created it with no contents, this results in an empty slice. Since no data can be appended to an empty slice, the number of bytes read is zero.

The `read_buf` method from 0.2 was removed due to its dependency on the `BufMut` trait, which is part of the bytes crate, and the bytes crate was removed from the public API due to not being 1.0. We plan to add a `read_buf` replacement to the tokio-util shortly.

The quickest way to fix it right now is to initialize the data first.

[1]: https://docs.rs/tokio/0.3/tokio/io/trait.AsyncReadExt.html#method.read
