### ISSUE TITLE
The tokio::net::udp module is empty

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2989]
The [`tokio::net::udp`][1] module is empty. Unless we add something to it during 0.3, we should remove it for 1.0.

[1]: https://docs.rs/tokio/0.3.0/tokio/net/udp/index.html

**Comment by sstelfox** [comment]
The contents are currently commented out pending the results of #2830. I'd personally like to see tokio include first class UDP support in the v1.0 milestone

**Comment by leshow** [comment]
@carllerche made a comment in #2830  that we would bring back `UdpFramed`. I've even got a branch based off my #2981 PR that brings it back, with some improvements because the underlying API is easier to use. I wanted to discuss what we were looking for. I was thinking of a `UdpFramed` along with `UdpFramedRead` and `UdpFramedWrite`, it could be created from a `UdpFramed::split` call if `UdpFramed` was to hold an `Arc<UdpSocket>`. That would give us all the functionality of the `0.2` `UdpFramed`. 

I'd love to hear suggestions about this though, but I think tokio should have support for `Stream` and `Sink` over udp, and right now `UdpFramed` is the only thing we've got that does that.

**Comment by LucioFranco** [comment]
Okay I think the right approach here is to `pub(crate)` the `udp` module and to bring it back in later iterations. We likely can put most of the things in there into `tokio_util::udp`.

**Comment by Darksonn** [comment]
Yeah, just remove the module for now. We can add it back if we added read and write halfs or some other udp utility.
