### ISSUE TITLE
fs: Re-use existing PathBuf in OpenOptions::open

### ISSUE THREAD

**Issue by ivan770** [tokio-rs/tokio#3142]
**Is your feature request related to a problem? Please describe.**
It seems that `OpenOptions::open` allocates a new PathBuf, even if one was used as `path` argument.
https://github.com/tokio-rs/tokio/blob/6259893094ebcdfecb107fcf3682eaad1bd1903b/tokio/src/fs/open_options.rs#L378-L379

**Describe the solution you'd like**
Replace `AsRef<Path>` bound with `Into<PathBuf>` (that would be incompatible with `std::fs::OpenOptions::open` signature)

**Describe alternatives you've considered**
None

**Comment by Darksonn** [comment]
This would be a breaking change, but I added the 1.0 milestone so we can consider changing.

**Comment by carllerche** [comment]
This API was picked to match `std`. The `open` syscall requires an allocation no matter what (currently done by std) in order to convert the path to a C string.

If we care about removing the second allocation, we can keep the same API and issue the syscall ourselves.

I vote for removing the 1.0 milestone.

**Comment by Darksonn** [comment]
Right, if it requires an allocation either way, then we should just close this, although I would be open to a PR that issues the syscall directly.

**Comment by carllerche** [comment]
If it is *measurable* then yeah, we should investigate fixing. I am going to close this issue for now though.
