### ISSUE TITLE
Why tokio::io::unix::AsyncFd::new is safe?

### ISSUE THREAD

**Issue by vi** [tokio-rs/tokio#3147]
[`tokio::fs::File::from_raw_fd`](https://docs.rs/tokio/0.3.3/tokio/fs/struct.File.html#impl-FromRawFd) is unsafe, but [`tokio::io::unix::AsyncFd::new`](https://docs.rs/tokio/0.3.3/tokio/io/unix/struct.AsyncFd.html#method.new) is safe.

Is it intentional or an oversight? It may be safe because of just polling around isn't expected to affect file descriptors too much. It may be unsafe because of typically things that allow specifying arbitrary file descriptor number are unsafe.

Either way safety should somehow be mentioned in documentation.

**Comment by Darksonn** [comment]
There was some discussion of this here: https://github.com/tokio-rs/tokio/issues/2728#issuecomment-702390485

> I don't think it needs to be unsafe. I don't believe there is any actual unsafety w.r.t working with an FD. I believe it is left over from early rust days when "unsafe" was used for things that were not strictly memory unsafe.

**Comment by vi** [comment]
> left over from early rust days when "unsafe" was used for things that were not strictly memory unsafe.

I expected that Rust standard library (and maybe custom libraries) relies on OS behaving sane, with memory safety at stake 

(e.g. using UNIX socket for synchronisation - receive cannot happen before send). Or using memory-mapped files internally.

`FromRawFd` allows accessing those "private" file descriptors. Either all file descriptors-based things should be considered untrustworthy and ineligible to be used for protecting safety (e.g. we cannot pass memory addresses over local sockets) or file descriptors are part of "safety zone" and certain operations regarding them should be marked unsafe, but we can rely that e.g. a socketpair we created stays as a socket pair at the end of the day, not being randomly replaced by something else entirely.

**Comment by MikailBag** [comment]
@vi I think this is a kind of grey zone (and also rabbit hole).

For example, you can do `File::create("/proc/self/fd/42").write("hi there")` to write any data to any fd. In general, any interaction with OS can lead to OS or other processes breaking our process in arbitrary way. For example imagine that user has following "program" running in background:
```
loop {
    if let Some(p) = find_process_by_author(vi) {
       let mem = open_process_memory(p);
       for _ in 0..1000 {
            mem[rand()] = rand();
       }
    }
}
```

It seems that rust spec should contain some list of assumptions that the environment is not too cruel (CPU doesn't have bugs, OS returns nonoverlapping chunks of memory in response to `mmap`, nobody will break our FDs and so on) to us and state that otherwise program behavior is undefined.
