### ISSUE TITLE
Problems to use tokio_util::context for tokio examples

### ISSUE THREAD

**Issue by carlosb1** [tokio-rs/tokio#3192]
**Version**
tokio-util v0.5.0
tokio v0.3.4

**Platform**
`Linux XXXX 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Description**
If it is no possible to create an example inside `tokio/examples` that it uses `tokio_util::context` dependency. It seems they are not exported correctly
[short summary of the bug]

I tried this code:
Well. it seems It happens in any example if we try to use `tokio_util::context` 
but my minimal code was:
```
use tokio_util::context::RuntimeExt;

fn main() {
....
..
.
}
```

I receive this error:

```
error[E0432]: unresolved import `tokio_util::context`
  --> examples/custom-executor-tokio-context.rs:11:17
   |
11 | use tokio_util::context::RuntimeExt;
   |                 ^^^^^^^ could not find `context` in `tokio_util`

```
I hoped I could compile without problems.

**Comment by davidbarsky** [comment]
I don't believe this is a bug, as Tokio's Cargo features are off by default. Try specifying the `tokio_util` dependency as:

```toml
tokio_util = { version = "0.5", features = ["rt"] }
```

**Comment by carlosb1** [comment]
I am not sure... the cargo.toml  has the flag `all` for features

**Comment by carlosb1** [comment]
https://github.com/carlosb1/tokio/blob/3192_add_rt_for_tokio_util/tokio-util/Cargo.toml <- here you have my fix, if the flag `all` uses rt

**Comment by Darksonn** [comment]
The [`examples/Cargo.toml`][1] specifies the following:

https://github.com/tokio-rs/tokio/blob/0acd06b42a9d1461302388f2a533e86d391d6040/examples/Cargo.toml#L13

The bug lies in `tokio-util` not including `rt` in the `full` feature.

https://github.com/tokio-rs/tokio/blob/0acd06b42a9d1461302388f2a533e86d391d6040/tokio-util/Cargo.toml#L22-L34

[1]: https://github.com/tokio-rs/tokio/blob/master/examples/Cargo.toml
