### ISSUE TITLE
Document that `task_local!` requires `rt-util` in tokio 0.2

### ISSUE THREAD

**Issue by malaire** [tokio-rs/tokio#3206]
**Version**
tokio 0.2.23

**Description**
Documentation of `tokio::task_local!` doesn't mention that it requires feature `rt-util`.

```
error[E0433]: failed to resolve: could not find `task_local` in `tokio`
   |
54 |     tokio::task_local! {
   |            ^^^^^^^^^^ could not find `task_local` in `tokio`
```

It should also be checked that 0.3 documentation for this macro is correct. It looks like `rt` feature might be required there which is not documented either. (But I didn't test this.)

**Comment by Darksonn** [comment]
Info for new contributors who wish to solve this issue:

To solve this, first see if it can be fixed by changing the `cfg_*` macros around it. Otherwise put an annotation like the following on it.
```rs
#[cfg_attr(docsrs, doc(cfg(feature = "rt-util")))]
```
Note also that a similar annotation appears to be missing on the `tokio::task::LocalKey` struct, although they are present on the struct's methods.

**Comment by Darksonn** [comment]
Reopening as the v0.2.x PR is still open.
