### ISSUE TITLE
Unbounded mpsc has blocking_recv but not blocking_send

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3268]
With #3262 we added a `blocking_recv` to the unbounded mpsc channel, without adding a `blocking_send` method. For consistency we should have either both or none of them.

Note that it was originally not added to the unbounded channel because you can just use an unbounded sync channel for that, which is [also descriped in the documentation][1]:

> **Unbounded channel:** You should use the kind of channel that matches where the receiver is. So for sending a message from async to sync, you should use the standard library unbounded channel or crossbeam. Similarly, for sending a message from sync to async, you should use an unbounded Tokio mpsc channel.

That said, I'm ok with adding the blocking methods.

The above documentation snippet should also be updated.

[1]: https://docs.rs/tokio/0.3/tokio/sync/mpsc/index.html#communicating-between-sync-and-async-code

**Comment by sunjay** [comment]
Does `UnboundedSender` need a `blocking_send` method? My understanding is that it [never blocks](https://docs.rs/tokio/0.3.5/tokio/sync/mpsc/struct.UnboundedSender.html#method.send) so that probably isn't necessary:

> This method is not marked async because sending a message to an unbounded channel never requires any form of waiting. Because of this, the send method can be used in both synchronous and asynchronous code without problems.

It's kind of misleading to call a method `blocking_send` when it will never block.

---

> Note that it was originally not added to the unbounded channel because you can just use an unbounded sync channel for that

I totally agree and I probably would have switched to a synchronous channel had I thought of that or if the documentation you suggested was present at the time. Is there any major downside to using an async channel in an async to sync context? I think I reached for it in my code because I was already using tokio for everything. It was natural to just keep using it in all contexts. (This is especially valuable when you don't want to bring in crossbeam as another dependency.)
