### ISSUE TITLE
Allow configuring tests to always run using the threaded scheduler with multiple threads.

### ISSUE THREAD

**Issue by masklinn** [tokio-rs/tokio#3332]
By default the tests runtime uses the basic scheduler, or so the panic message says.

This is an issue when the tests ultimately call something which blocks in place e.g. [sqlx/sqlite](https://github.com/launchbadge/sqlx/issues/713#issuecomment-742805514) (despite the thread being about actix, the same issue occurs using the tokio scheduler).

The tests [can be opted into the threaded scheduler on an individual basis](https://github.com/tokio-rs/tokio/issues/1838#issuecomment-565895955) but odds are when the system under test starts requiring the threaded scheduler just about every test will need it. Having to flag every test with `test(threaded_scheduler)` quickly gets long in the tooth, and because it's an attribute there's no way to create a quick utility macro.

I tried disabling all default features and only enabling the threaded scheduler, but it seems to have no effect (I expect because the threaded scheduler also enables the core stuff and the default doesn't change). I also tried to use `tokio_macro` directly but at least for 0.2 (because warp) it doesn't seem like [`test_threaded`](https://docs.rs/tokio-macros/0.2.6/tokio_macros/attr.test_threaded.html) uses the multithreaded scheduler by default? The panic message seems to be the same.

Incidentally there's a bit of an inconsistency / oddity, possibly in the error message only: the documentation states that `core_threads=1` suffices to select the multithreaded runtime, however using that does not work, the panic message remains

> can call blocking only when running on the multi-threaded runtime

I don't know if `core_threads=1` doesn't actually select the multithreaded runtime (and the message is correct) or the message really says that it can't move work between threads because there aren't other threads to move to (which makes sense for both single-threaded scheduler and multi-threaded scheduler with only one thread). The latter doesn't seem to make much sense as my understanding is tokio should be able to spawn up to `max_threads` (inclusive of the one core thread), which should default to 512?

**Comment by Darksonn** [comment]
I don't think this is possible to do. The only real way to configure something globally is features, and features should not change behavior of code that compiles without it — only allow new code to be written.

Regarding the variants of the test macro in the tokio-macros crate, the difference is that `test_basic` emits a compile-time error if you try to select the multi-threaded scheduler with `test(threaded_scheduler)`, whereas `test_threaded` will configure the threaded scheduler when you select it. Conditionally exposing different versions of the macro depending on feature flags is how Tokio is able to tell tokio-macros which feature flags are enabled, allowing the macro to emit good error messages if you try to use a feature that is not enabled. Of course, due to the feature flag rule I mentioned above, their behavior must be identical if you do something that compiles with `test_basic`.

As for `core_threads=1`, that has to do with the builder. The macro uses the basic scheduler when its set to 1, but the runtime builder doesn't. It is now clear that this is a mistake, and the macro has been fixed on this front in more recent versions of Tokio.

As for the 512 max number of threads, a basic runtime is not able to spawn new worker threads, only blocking threads. Since `block_in_place` turns a worker thread into a blocking thread, it needs to be able to spawn a new worker thread to take over while it is blocking, but the basic runtime can't do this.

In my opinion here the mistake is the use of `block_in_place`. You should be using `spawn_blocking`.

**Comment by masklinn** [comment]
> I don't think this is possible to do. […]

Thanks for the insight. Maybe Tokio (or even just `tokio_macros`) could expose a test macro which straight uses the threaded scheduler always? That way it could be `use`’d `as test` for convenience?

> As for `core_threads=1`, that has to do with the builder. The macro uses the basic scheduler when its set to 1, but the runtime builder doesn't. It is now clear that this is a mistake, and the macro has been fixed on this front in more recent versions of Tokio.

Good news, i guess I’ll be slightly less confused when I get to use that. Though `test(threaded_scheduler)` is clearer anyway. 

> In my opinion here the mistake is the use of `block_in_place`. You should be using `spawn_blocking`.

Ok i should probably ask the sqlx folks why they’re using `block_in_place` then.

**Comment by Darksonn** [comment]
> Thanks for the insight. Maybe Tokio (or even just tokio_macros) could expose a test macro which straight uses the threaded scheduler always? That way it could be use’d as test for convenience?

It wont get into Tokio proper, but maybe we could add it in tokio-macros.

However I think it's simpler if you just fork tokio-macros and publish a crate with the updated default.
