### ISSUE TITLE
TcpStream::connect unexpected successful connection

### ISSUE THREAD

**Issue by emilliken** [tokio-rs/tokio#3405]
Tokio version 1.0.1 on Linux kernel 4.19

When using TcpStream::connect() to connect to a port on 127.0.0.1, sometimes the source port matches the destination port, which causes the connect() to return Ok() and succeed, even if the destination port was closed prior to running connect().

see:
```rust
use tokio::net::TcpStream;

const TARGET: &str = "127.0.0.1:56064";

#[tokio::main]
async fn main() {
    let mut i: u64 = 0;

    loop {
        i += 1;

        if let Ok(strm) = TcpStream::connect(TARGET).await {
            let lcl = strm.local_addr().unwrap();
            let peer = strm.peer_addr().unwrap();

            println!("open! i = {}, lcl = {}, peer = {}", i, lcl, peer);
        }
    }
}
```
running this prints:
open! i = 9647, lcl = 127.0.0.1:56064, peer = 127.0.0.1:56064
open! i = 23763, lcl = 127.0.0.1:56064, peer = 127.0.0.1:56064
open! i = 37879, lcl = 127.0.0.1:56064, peer = 127.0.0.1:56064

I expected no output.

**Comment by malaire** [comment]
That isn't a bug but expected behaviour. If target port is in [ephemeral port range](https://en.wikipedia.org/wiki/Ephemeral_port) and it is not currently in use, then there is a chance of client getting assigned target port number and so it connects to itself.

See also: [socket getting created with same IP and port on local host](https://stackoverflow.com/questions/4021271/socket-getting-created-with-same-ip-and-port-on-local-host).

**Comment by emilliken** [comment]
ah, you are right.  A C program I just wrote has the same behavior.  Thanks
