### ISSUE TITLE
meta: tweak post 1.0 dev/release process

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#3411]
Now that we are post 1.0, we should tweak our dev process to match [semver](https://semver.org/):

* v1.x.0 - new functionality
* v1.0.x - bug fixes

This means we need to tweak our git workflow to handle applying bug fixes to all branches.

## Proposal

New functionality is always merged to master. When a new minor version is released, we create an associated branch. For example, we would have a `tokio-1.0.x` branch, `tokio-1.1.x`, `tokio-1.2.x`, etc...

Bug fixes are applied to the appropriate `tokio-1.[n].x` branch. A *merge commit* is used to forward port bug fixes from `tokio-1.[n].x` branches to `master`.

**Comment by Darksonn** [comment]
I assume we will need some sort of configuration change to allow making real merge commits to master. As for how we make the merge, it seems like we should just be able to open a PR that wants to merge the `tokio-1.[n].x` branch into master directly, but maybe it is better to put a temporary branch on top of `tokio-1.[n].x` first?

I added an `tokio-1.0.x` branch pointing at the `tokio-1.0.1` release tag. Since then, we've had both bug-fixes, doc-changes and new features. Would you move some of those bug-fixes to an `tokio-1.0.2` release?

**Comment by Darksonn** [comment]
It seems best to me to only make patch releases if there's a bug we want to fix quickly.

**Comment by carllerche** [comment]
@Darksonn 

> It seems best to me to only make patch releases if there's a bug we want to fix quickly.

We could use that as a rule of thumb: use a patch release if we want to release immediately after the PR lands.
