### ISSUE TITLE
Need a Handle for UdpSocket::from_std

### ISSUE THREAD

**Issue by main--** [tokio-rs/tokio#349]
(Creating an issue for this as [requested](https://github.com/tokio-rs/tokio/pull/308#issuecomment-387536202) by @carllerche)

Creating a `tokio::net::UdpSocket` from an `std::net::UdpSocket` using [`from_std`](https://docs.rs/tokio/0.1.6/tokio/net/struct.UdpSocket.html#method.from_std) requires a `&Handle`. As the single threaded runtime doesn't expose one, the only workaround I found is to call wrap a `future::lazy` around the code and call `Handle::current()` in there. While calling `Handle::current()` without the lazy future appears to work as well, it creates a thread (for no reason? I don't understand this part).

**Comment by carllerche** [comment]
Ah yes! This makes sense (thanks for opening the issue).

The right way **should** be to use `Handle::default()`, but it doesn't quite work today due to #307. I plan on fixing this soon.

Once #307 is handled, you will not need to use the `future::lazy`.

On top of fixing #307, documentation for APIs that take `&Handle` should include a snippet on how to get a `Handle`.

**Comment by main--** [comment]
Thanks for the explanation, now I understand what's going on.

**Comment by carllerche** [comment]
#350 fixed the functionality problem, all that is left is improving the docs.
