### ISSUE TITLE
Make sure coop system never consumes permits without actually performing work

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3502]
As initially described in https://github.com/tokio-rs/tokio/issues/3493#issuecomment-772880013, it is noted that if the coop system consumes a permit without doing any work, this can cause a deadlock.

One instance of this is found here:

https://github.com/tokio-rs/tokio/blob/cc97fb8a5ff6ef17f6dc9968fbbe67002cff4130/tokio/src/time/driver/sleep.rs#L216-L221

This issue tracks finding all such instances, and should not be closed until we are confident that we have fixed all of them.

**Comment by jonhoo** [comment]
I'm not sure I follow why the indicated code is buggy? The point of the call to `made_progress` inside of `map` is to make it so that if progress _isn't_ made, the budget is not consumed. That is, if `coop` is dropped without `made_progress` being called, the budget is restored to what it was prior to the call to `poll_proceed`. So that code looks right to me.

**Comment by Darksonn** [comment]
I agree. I think the implementation is right.
