### ISSUE TITLE
Create `tokio-util` crate

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#354]
Most types / fns / etc.. that are not expected to be part of any libraries that depend on tokio's *public* api should be extracted to a `tokio-util` crate. This allows the foundational crates to provide greater amounts of stability while allowing the `tokio-util` crate to make breaking changes more often.

The `tokio-util` crate would maintain a module structure similar to `tokio` and the `tokio` crate would re-export the contents of `tokio-util`.

This issue is a meta issue tracking required changes to make this happen.

* Move `length_delimited` (#101, #105).
* Move utility codecs `BytesCodec` and `LinesCodec` (#353).
* `io::*` fn helpers from tokio-io.

**Comment by carllerche** [comment]
I actually am wondering if `BytesCodec` and `LinesCodec` should be moved...

**Comment by carllerche** [comment]
As an initial step, `length_delimited` can be copied into `tokio:util`. The crate can be extracted in the future.

**Comment by carllerche** [comment]
This issue should also be handled incrementally in multiple PRs. I think the best process is:

1) PR moving `length_delimited`
2) PR moving + refreshing io helpers.
3) Extract code -> tokio-util

**Comment by carllerche** [comment]
I'm actually wondering if a separate crate is needed. Nothing in tokio-util should be exposed by third party crates as part of their public API.

Instead, I'm wondering if it all should just stay in the `tokio` crate and we add feature flags to be able to pick and choose what components to pull in.

**Comment by kpp** [comment]
> io::* fn helpers from tokio-io.

Most of them were ^C^V into https://github.com/rust-lang-nursery/futures-rs/tree/master/futures-util/src/io so we'd rather move to futures 0.3

**Comment by carllerche** [comment]
There currently is no plan to move to futures 0.3. That branch is experimental and does not work on Rust stable. Once it stabilizes, we can start looking at it.

**Comment by phungleson** [comment]
Hey, I have some free time and want to help here and there with rust, this seems to be an easy task.

Generally, it seems like having a separate crate might be a better option in the long run, i.e. easier extension and maintenance, especially for cases like `util`, but certainly there are things I am not aware of.

Let me know what you prefer @carllerche, happy to help one way or the other or just park this for further consideration.

**Comment by hawkw** [comment]
Hi @phungleson, I believe the current plan is to move this code into the `tokio` crate, rather than creating a new `tokio-util` crate. I've already merged a PR (#568) to move `length_delimited` from `tokio-io` into `tokio`; I'd be happy to help provide guidance if you want to work on the remaining work for this issue?

**Comment by phungleson** [comment]
Cool thanks @hawkw yep let me know.

**Comment by hawkw** [comment]
@phungleson Alright, I've already moved the length-delimited code in #568, and `BytesCodec` and `LinesCodec` were moved to `tokio-codec` in #360. So, I think that all that's left at this point is to move the code in [this module](https://github.com/tokio-rs/tokio/blob/6e45e0ac61b68208310748a61f68dc6df576dbb6/tokio-io/src/io/mod.rs) from the `tokio-io` crate to the `tokio` crate's module `io`.

Here are a couple things you'll want to keep in mind:
1. In order to avoid a breaking change, rather than deleting the code in the current location, we'll want to "soft-delete" it instead, by deprecating it & hiding it from the docs. You can use 1ead065a18b6410ef2d89a36c96b794e235940a3 as an example of how to do that.
2. Once you've moved the code to its new location in `tokio`, you'll probably have to update the imports in the moved code. The `tokio` crate depends on the `tokio-io` crate, so you can basically just prefix any stuff that code imported from other files in that crate with `tokio_io::<WHATEVER>`. 
3. You'll want to update any of the examples and tests that depend on the code you're moving to use it in the new location, so they don't warn about using deprecated code. You can find any uses of the deprecated code by running the tests with `cargo test` and compiling the examples with `cargo build --example <NAME_OF_EXAMPLE>` and seeing if it warns about deprecated code.

I hope that's enough to get you started --- let me know if you have any additional questions!

**Comment by phungleson** [comment]
Cool thanks so much @hawkw it is very detailed :D shouldn't have any issues :D

**Comment by phungleson** [comment]
Hey @hawkw and others I have some work done and have 2 questions, perhaps you can help?

**Comment by carllerche** [comment]
We opted to not do this, instead `tokio` includes feature flags to enable / disable functionality.
