### ISSUE TITLE
Add owned permits to mpsc channel

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3688]
The `mpsc::Sender::reserve` method currently returns a permit that borrows from the `Sender`. It would be nice to have a version of it that takes an `Arc<Sender>` and returns an owned permit.

**Comment by hawkw** [comment]
+1 for this.

It would also be nice if there was a method on `tokio-util`'s `PollSender` that polls to acquire a permit (which would be possible after adding an owned permit type to `Sender`. Currently, the `PollSender::poll_send_done` method returns ready if _the sender it's called on_ isn't currently sending; if the channel is at capacity, it can still return ready, and a message can be moved into the future stored by that sender. Essentially, this gives `PollSender` capacity for (`bound `+ `n_senders`) messages, rather than `bound`. This issue could be avoided if `PollSender` also provided a method to poll to reserve send capacity, rather than to complete a current send.

I'd be happy to work on both of these API additions if we think this change is a good idea.

**Comment by Darksonn** [comment]
I would be happy to see such PRs!

**Comment by hawkw** [comment]
> It would be nice to have a version of it that takes an `Arc<Sender>` and returns an owned permit.

After a little thought, I'm not actually sure if it's ideal to have this take an `Arc<Sender>` --- the channel is already reference counted internally, so it seems like a shame to require users to introduce a second, unnecessary layer of refcounting around it. Instead, we could just take the `Sender` by value, and document that users can trivially clone it, or we could take the sender by reference and perform the clone internally. IMO, it's probably best to take it by value, since that's closer to the `Arc<Semaphore>::acquire_owned` API.

On the other hand, there's one real argument for requiring the `Arc`, which is that the API would look more similar to `Semaphore`'s `acquire_owned`. But I don't think that consistency is worth introducing an unnecessary additional layer of ref counting.

What do you think?

**Comment by Darksonn** [comment]
I suppose that makes sense. It's a bit unfortunate that `PollSender` in tokio_util uses `Arc` then.

**Comment by davepacheco** [comment]
Thanks for this!  I was just needing this and used it successfully on the main branch.  Any idea when this will show up in a crates.io release?

**Comment by Darksonn** [comment]
We don't yet have a fixed schedule for releases, so that would be next time someone gets around to making a release.
