### ISSUE TITLE
tokio::time::advance()'s behavior is confusing, skips over other sleep deadlines

### ISSUE THREAD

**Issue by sbrocket** [tokio-rs/tokio#3985]
**Version**
tokio 1.8.1 (appears to be what Rust Playground is using)

**Platform**
N/A (Rust Playground)

**Description**

tokio::time::advance() causes Sleep tasks to be skipped over; see the Rust Playground example test below. It is easy enough to just use tokio::time::sleep() in its place instead...but then it is unclear what advance()'s purpose is or why its current behavior is to skip over deadlines.

At the very least, it seems like the documentation should be improved so that others like myself don't lose time rediscovering this.

Minimal test: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ec3bbec1a9642eda37a50bec26f39485

**Comment by sbrocket** [comment]
A Discord user pointed out that a `tokio::task::yield_now().await` call after the `advance` causes the test to pass. However, this makes even less sense because `advance` already calls `yield_now()` and returns that future. Indeed `advance(Duration::from_secs(0)).await` after the first advance also makes the test pass. This makes it look more like something is broken, rather than just unclear.

**Comment by Darksonn** [comment]
It doesn't work because the runtime did not get around to starting the spawned task until after the `assert!(done.load(Ordering::SeqCst))` call had completed.

**Comment by sbrocket** [comment]
Maybe I’m missing something, but why does that make sense? advance’s yield_now() call should give any other pending tasks - including the spawned task, right? - a chance to run, shouldn’t it?

**Comment by Darksonn** [comment]
Hm, maybe my statement is wrong.

Anyway, all that `advance` does is make sure that all sleep calls whose target time you advanced past will complete next time the runtime polls them. There's no guarantee that the runtime will actually have polled them before `advance` returns.

**Comment by sbrocket** [comment]
> There's no guarantee that the runtime will actually have polled them before advance returns.

Sure, not before it returns. But `advance()` also calls `yield_now()` and returns that future, so `advance(duration).await` *should* have polled them.

**Comment by sbrocket** [comment]
Let me phrase this another way: How is `advance`'s behavior intended to differ from `sleep`? In what case would someone want or need to use `advance().await` rather than a sleep of the same duration?

**Comment by Darksonn** [comment]
What actually happened is that the runtime will poll up to 61 ready tasks before it drives the IO and timer drivers, so the task was polled before the timer driver was touched after the advance.

The difference between `advance` and `sleep` is that `advance` always returns immediately, but `sleep` doesn't. It's true that you usually will need only `sleep`.

**Comment by loyd** [comment]
I'm also surprised by this change in behavior. The previously used version was v1.5 and after the update, my tests stop passing. Strongly speaking, it's a breaking change and shouldn't be done at all.

Now I don't see any reasons to call `advance` without following `yield_now` or just `sleep`. 

>  is that advance always returns immediately
Mm.. but `advance` is marked as `async fn`, that's illogical in this case.

**Comment by Darksonn** [comment]
@loyd It sounds like you are referring to the change in #3712? That was a bug-fix where advancing the time would advance it too far.

**Comment by Darksonn** [comment]
Another way to explain the behavior of `advance` is that it behaves as if you have [blocked the thread](https://ryhl.io/blog/async-what-is-blocking/) for the given duration. When the runtime notices that this has happened, all sleeps with a deadline before the new current time become ready, and the runtime will poll them in any order.

In general, the runtime promises very little about the order in which things are polled, and there are lots of people who assume that it guarantees much more than it does. This also comes up with `yield_now()`, see e.g. #4091. All that the runtime guarantees when you use `advance` is that next time the runtime becomes idle or auto-advances the timer, all sleeps with a deadline less than the new current time will have completed. In particular:

 1. The sleeps all complete at "the same moment" even if their deadlines are different, so they may be polled in a different order than their deadlines.
 2. The sleep might not complete the first time it gets polled after the call to `advance`. (But if it doesn't, the runtime will poll it again until it completes before the runtime becomes idle or auto-advances the timer.)

All of the behavior above is consistent with what happens when you block the thread. I agree that it would make more sense for the function to not be async, but we can't do anything about that now.

The behavior of `advance` has never been the same as `sleep`, even before the bug-fix mentioned in the post above.

**Comment by Darksonn** [comment]
My understanding of the behavior is that most invocations of `tokio::time::advance()` should be a call to `tokio::time::sleep()` instead.
