### ISSUE TITLE
sync::mpsc::channel is doing undesirable calls to std::thread::yield_now

### ISSUE THREAD

**Issue by neivv** [tokio-rs/tokio#4034]
**Version**
1.9.0

**Platform**
Windows 10 20H2 64-bit, running 32-bit code

**Description**

These `yield_now` calls seem to be intended for testing with loom, and not cause actual yields outside tests, as a comment is implying here
https://github.com/tokio-rs/tokio/blob/1e95d6994a78d880df79d9e2ed207c908e89ac1a/tokio/src/sync/mpsc/block.rs#L347-L348 

And `sync::mpsc::list` has some yields that likely don't need to be even a spin hint, as they seem to be on a code path that isn't really a spin loop. Though I'm certainly not an expert here.

Either way, today these calls do go to `std::thread::yield_now`.

I'm seeing async tasks sometimes being heavily deprioritized by the OS under heavy load situations, and these yields seem to be causing this.

**Comment by hawkw** [comment]
> Either way, today these calls do go to `std::thread::yield_now`.

Ah, yup, it looks like the non-mocked version of the `loom` module just re-exports `std::thread`: https://github.com/tokio-rs/tokio/blob/1e95d6994a78d880df79d9e2ed207c908e89ac1a/tokio/src/loom/std/mod.rs#L96 so those calls are calling `thread::yield_now` when not testing with loom, rather than `spin_loop_hint`. We should fix that.
