### ISSUE TITLE
Suggestion: implement Stream for time::Interval

### ISSUE THREAD

**Issue by bnoordhuis** [tokio-rs/tokio#4088]
I frequently want a "ticker" that ticks a fixed number of times before expiring. I can accomplish that through e.g. `futures::stream::unfold()` but that's neither efficient or ergonomic:
```rust
let interval = tokio::time::interval(Duration::from_secs(1));

let interval = futures::stream::unfold(interval, |mut interval| {
    async {
        let instant = interval.tick().await;
        Some((instant, interval))
    }
    .boxed_local()
});

let mut interval = interval.take(30);

while interval.next().await.is_some() { /* ... */ }
```
It would therefore be exceedingly nice if `Interval` supported that pattern directly.

<hr>

edit: forgot to mention I'm aware of `tokio::stream::IntervalStream` but I don't understand why it's external to `Interval` - it'd make more sense to me to implement it directly on the type.

**Comment by Darksonn** [comment]
Just do this:
```Rust
let mut interval = tokio::time::interval(Duration::from_secs(1));
for _ in 0..30 {
    interval.tick();
    /* ... */
}
```

**Comment by bnoordhuis** [comment]
The code in my example is abbreviated for legibility. The code base I lifted it from has the interval as a branch in a `tokio::select!` statement.

I edited the issue just before you posted but in case you missed it: I know `tokio::stream::IntervalStream` exists but I don't get why it's an external type when it could be implemented directly on `Interval`.

**Comment by Darksonn** [comment]
It is not implemented directly on `Interval` because `Stream` is defined in the `0.x` crate futures, and we do not have any `0.x` crates in the public API of Tokio. Still, if you are aware of `IntervalStream`, I'm not sure why you don't just do
```Rust
let interval = tokio::time::interval(Duration::from_secs(1));
let mut interval = IntervalStream::new(interval).take(30);
/* ... */
```

**Comment by bnoordhuis** [comment]
Okay, that makes sense. Would that change if/when either futures goes 1.x or `std::stream::Stream` is stabilized?

> if you are aware of IntervalStream, I'm not sure why you don't just do [..]

It means taking on the additional dependency of tokio-stream and we're somewhat size conscious.

**Comment by Darksonn** [comment]
We would definitely add the `Stream` impls if the trait is added to the standard library. I encourage you to check out the documentation for the empty [`tokio::stream`][1] module. Back when Tokio 1.0.0 was released, we were all naively thinking "`Stream` in std is gonna land any day now", but it hasn't happened yet now 9 months later.

You can get a `Stream` impl using [`poll_fn`][2] instead of `unfold` like this:
```Rust
futures::stream::poll_fn(move |cx| interval.poll_tick(cx).map(Some))
```
I am inclined to say that we don't want to add this feature because there are several simple ways to get the behavior you are looking for using the existing combinators.

[1]: https://docs.rs/tokio/1/tokio/stream/index.html
[2]: https://docs.rs/futures/0.3/futures/stream/fn.poll_fn.html

**Comment by Darksonn** [comment]
Closing since our policy on implementing `Stream` is already fixed, and we are not going to do so at this time.

**Comment by bnoordhuis** [comment]
Thanks for the explanation and the `poll_fn` suggestion, much appreciated.
