### ISSUE TITLE
polish: add `#[track_caller]` to functions that can panic

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#4413]
Our current [MSRV](https://github.com/tokio-rs/tokio#supported-rust-versions) is 1.46, which introduced [track_caller](https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html) which can be used to make panic messages better. 

We should ensure that all methods that *can* panic when misused are annotated with `#[track_caller]` so the panic message includes the file/line where the *user* called the Tokio method instead of showing the file/line inside the Tokio source. If the panic is a few calls deep in Tokio, then I believe each internal method needs its own `#[track_caller]`

One example where this should be done: [`Handle::current()`](https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/handle.rs#L116), but there probably are others.

Ideally, we also add tests that verify the behavior.

**Comment by hds** [comment]
With the merging of that last PR, I think that this issue could be considered complete. The `#[track_caller]` attribute has been added to all public, stable APIs where possible.

I searched the tokio repo for `# Panics`, i.e. places where the documentation indicates that a panic may occur when a function is used incorrectly. I then went through them all and added the attribute and tests. Functions were excluded when the call stack passed through either a closure, block, or async function as `#[track_caller]` cannot be applied to those. Each PR details the functions which could not be covered.

* tokio: 
  * io: #4793
  * macros: macros don't need `#[track_caller]`
  * net: #4805
  * park: Panic headings only in `Park` trait
  * runtime: #4772
  * signal: #4806
  * sync: #4808
  * task: #4848
  * time: #4791
* tokio-stream: #4786
* tokio-util: #4785

Note: Unstable APIs were excluded.

CC @Darksonn (since you approved most of the PRs in this set and have been generally amazing with your quick feedback and help - Thank you!)

**Comment by Darksonn** [comment]
How many functions were you unable to apply `#[track_caller]` to? I don't really have a good overview of the count.

**Comment by hds** [comment]
And while doing the counts, I realized that I missed one case where the `rt` feature is disabled, I've just created a small PR to add this: #4852.

**Comment by carllerche** [comment]
Closing as there are no more immediate steps to take. Follow up issues can be opened for more targetted work if needed.
