### ISSUE TITLE
bytes remaining on stream

### ISSUE THREAD

**Issue by 21pages** [tokio-rs/tokio#4978]
**Version**

tokio v1.20.1
tokio-util v0.7.2 (*)

**Platform**
64-bit (Windows)

**Description**

[short summary of the bug]

"bytes remaining on stream" occur frequently.
[https://docs.rs/tokio-util/0.7.3/src/tokio_util/codec/decoder.rs.html](https://docs.rs/tokio-util/0.7.3/src/tokio_util/codec/decoder.rs.html), line 151

**Comment by Darksonn** [comment]
So what is the bug?

**Comment by 21pages** [comment]
It can't be called a bug, but it happens frequently and I would like to know how to avoid it.

**Comment by hds** [comment]
In the documentation for [`decoder_eof`](https://docs.rs/tokio-util/0.7.3/tokio_util/codec/trait.Decoder.html#method.decode_eof) it states that that specific error will be returned if `self.decode(buf)` (called from within `decode_eof` returns `Ok(None)` **and** there are still bytes in the buffer.

If you look at the docs for [`decode`](https://docs.rs/tokio-util/0.7.3/tokio_util/codec/trait.Decoder.html#tymethod.decode), you'll see that the expected conditions for it to return `Ok(None)` are:
* contents of the buffer look valid
* contents of the buffer is **not** enough to construct a whole frame

So, essentially the buffer contains a partial frame. This is why the error is returned, you've reached the EOF (End of File), but the decoder is stating that it has a partial frame only (which implies that it is expecting more data).

In case you need to "construct frames _across_ eof boundaries" or if you expect to have a different data structure at the end of the stream, then you may need to implement your own `decode_eof` instead of using the one provided by the trait.

**Comment by 21pages** [comment]
> In the documentation for [`decoder_eof`](https://docs.rs/tokio-util/0.7.3/tokio_util/codec/trait.Decoder.html#method.decode_eof) it states that that specific error will be returned if `self.decode(buf)` (called from within `decode_eof` returns `Ok(None)` **and** there are still bytes in the buffer.
> 
> If you look at the docs for [`decode`](https://docs.rs/tokio-util/0.7.3/tokio_util/codec/trait.Decoder.html#tymethod.decode), you'll see that the expected conditions for it to return `Ok(None)` are:
> 
> * contents of the buffer look valid
> * contents of the buffer is **not** enough to construct a whole frame
> 
> So, essentially the buffer contains a partial frame. This is why the error is returned, you've reached the EOF (End of File), but the decoder is stating that it has a partial frame only (which implies that it is expecting more data).
> 
> In case you need to "construct frames _across_ eof boundaries" or if you expect to have a different data structure at the end of the stream, then you may need to implement your own `decode_eof` instead of using the one provided by the trait.
> 
> Also, just a hint for the future. If you're seeking help for something that can't be called a bug, then you're probably better off creating a discussion instead of an issue: https://github.com/tokio-rs/tokio/discussions

thanks
