### ISSUE TITLE
Tokio-util codec Framed - cancel safety 

### ISSUE THREAD

**Issue by gopakumarce** [tokio-rs/tokio#5310]
Hi,

I cant see anywhere in the docs about the cancel safety of FramedRead and FramedWrite. Can anyone pls point me to any doc/code comments/anything that says whether those are cancel safe or not ?

Rgds,
Gopa.

**Comment by Darksonn** [comment]
The documentation for `tokio::select!` has [a section][1] that lists some cancel safe methods. In particular, it mentions that `StreamExt::next` is cancel safe no matter what the stream is. Since `FramedRead` is a stream, the `next` method is cancel safe on them.

As for the sink methods on `FramedWrite`, well, if `send` is used as the event in a [tokio::select!](https://docs.rs/tokio/latest/tokio/macro.select.html) statement and some other branch completes first, then it is guaranteed that the message was not sent. That said, the message you're trying to send is lost if you cancel the `send` call.

[1]: https://docs.rs/tokio/latest/tokio/macro.select.html#cancellation-safety
