### ISSUE TITLE
Add support for #[tokio::test(thread_stack_size=X)]

### ISSUE THREAD

**Issue by nickb937** [tokio-rs/tokio#5399]
**Is your feature request related to a problem? Please describe.**

With large end-to-end style unittests, which execute over 100+ async functions, it is quite easy to hit Stack Overflow exceptions.  Sometimes this is outside the control of the unittest, for example the `nom` library used by `sqlx` to parse SQL statements for pretty-printing seems to use a lot of stack space, so enabling logging of sql statements can cause the unittest to fail.

**Describe the solution you'd like**

What I want is the ability to explicitly change the default 2MB stack size in the `tokio::test` macro

    #[tokio::test(thread_stack_size=X)]

because there are other macros applied at the function that have a dependenent ordering:

```rust
#[tokio::test]
#[serial]
#[named]
async fn test_find_contract_effective_date_range() -> Result<(), DbErr> {
```

**Describe alternatives you've considered**

Two alternatives exist:

1. Building tests with optimisations enabled:

```
[profile.test]
opt-level = 1
```

2. Explicitly instantiate the runtime builder, but this seems to counter the purpose of having a convenience macro.

```
runtime::Builder::new_multi_thread()
    .thread_stack_size(4 * 1024 * 1024)
```

3. Disabling `sqlx` logging, which makes it hard to run a test and monitor the sql statements.

**Comment by Darksonn** [comment]
The `#[tokio::test]` macro uses the current-thread runtime by default, which doesn't spawn threads. Because of that, the option wouldn't do anything unless you also set it to use the multi-threaded runtime. Furthermore, it would only affect code in spawned tasks (in `tokio::spawn`), since the main function of the test runs in a `block_on` call, which means that it doesn't run on a Tokio-owned thread.

You might want to use the `RUST_MIN_STACK` environment variable for this instead. That should affect tests.

**Comment by nickb937** [comment]
Ok, fair enough.  I've solved the problem in a different way by compiling the tests with optimisation turned on
