### ISSUE TITLE
Crates that depend on a crate using Tokio with `tokio_unstable` also need to enable that feature

### ISSUE THREAD

**Issue by matthunz** [tokio-rs/tokio#5405]
**Version**
tokio = { version = "1.24.2", features = ["macros"] }

**Platform**
All platforms

**Description**
Currently it looks like any crate that uses `tokio_unsable` will have to specify that anyone who uses that crate will also have to enable `tokio_unstable`. This seems like a huge ergonomics issue as any crates released using Tokio's unstable features will have to inform users they also need to enable that feature just to build their crate.

Is there a better way of enabling that feature in a library crate?

**Comment by Darksonn** [comment]
This is intentional. We _want_ libraries to have to tell the end-user about it.

We have seen in other projects how changes to the unstable parts of the library result in just as much breakage as a real breaking change when `unstable` is just an ordinary cargo feature that any library can silently enable.
