### ISSUE TITLE
OwnedMutexGuard is missing a mapped version

### ISSUE THREAD

**Issue by craftytrickster** [tokio-rs/tokio#5414]
I would like for `.map` to exist on the [OwnedMutexGuard](https://docs.rs/tokio/latest/tokio/sync/struct.OwnedMutexGuard.html) the same way it currently exists on [MutexGuard](https://docs.rs/tokio/latest/tokio/sync/struct.MutexGuard.html#method.map).

**Comment by Darksonn** [comment]
We've had soundness issues due to mapping mutex guards in the past (see e.g. #2472, #3344), so I would like to first verify that this addition is sound.

@Amanieu Do you know whether there is any issue with adding a method for mapping on our owned mutex guard? We already have it on the non-owned guard.

**Comment by Amanieu** [comment]
`OwnedMutexGuard::mutex` gives access to the original `Arc<Mutex<T>>`, which won't work after mapping. So you do need a separate type.

**Comment by Darksonn** [comment]
Ok, that makes sense. We will go for a new separate type.

**Comment by Darksonn** [comment]
I figured out why we don't already have this: it's super annoying to implement.
