### ISSUE TITLE
Need confirmation on whether high-risk lines produce deadlock

### ISSUE THREAD

**Issue by amab8901** [tokio-rs/tokio#5482]
These lines were identified (https://github.com/tokio-rs/tokio/issues/5479) as having high probability of producing deadlocks (as in https://github.com/tokio-rs/tokio/issues/5429):
- [ ] task/atomic_waker.rs
  - 204
- [ ] broadcast.rs
  - 915
- [ ] notify.rs
  - 771
  - 835
  - 874
- [ ] oneshot.rs
  - 427

I think we need to create some kind of tests to verify whether they actually can cause deadlocks.

**Comment by Darksonn** [comment]
I took a look at them:

 1. `task/atomic_waker.rs` - this one already handles panics correctly, and there's no mutex so it cannot deadlock
 2. `broadcast.rs` - This assignment only happens if the field is `None`, so it cannot run the destructor of a waker.
 3. `notify.rs` - will be fixed by [#5471](https://github.com/tokio-rs/tokio/pull/5471)
 4. `oneshot.rs` - This uses `ptr.write`, which doesn't run the destructor of old values, so it isn't vulnerable.
