### ISSUE TITLE
tokio-util DelayQueue wheel panics if it exists for more than 2^36 milliseconds

### ISSUE THREAD

**Issue by Skepfyr** [tokio-rs/tokio#5536]
**Version**
```
├── tokio v1.26.0
│   └── tokio-macros v1.8.2 (proc-macro)
└── tokio-util v0.7.7
    └── tokio v1.26.0 (*)
```

**Platform**
x86_64 GNU/Linux 5.15.90.1

**Description**
If a `DelayQueue` exists for more than 2^36 milliseconds (2 years 64 days 21 hours 7 minutes 4.7856432 seconds) then all inserts will start panicking with the following error message:
```
thread 'main' panicked at 'index out of bounds: the len is 6 but the index is 6', /home/user/.cargo/registry/src/git.datcon.co.uk-266cfbb8aad8092e/tokio-util-0.7.7/src/time/wheel/mod.rs:108:9
```

This can be reproduced with the following code:
```rust
use std::time::Duration;
use futures::StreamExt;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    tokio::time::pause();
    let mut queue = tokio_util::time::DelayQueue::new();
    for _ in 0..2 {
        tokio::time::advance(Duration::from_millis(1 << 35)).await;
        queue.insert(0, Duration::from_millis(0));
        queue.next().await;
    }
    queue.insert(1, Duration::from_millis(1));
}
```

My understanding of this bug is that this is caused by the `level_for` function on the wheel returning 6 if the `elapsed` and `when` variables differ in the 36th bit (or more) but are less than MAX_DURATION apart.

**Comment by Skepfyr** [comment]
There are a bunch of fixes for this in `tokio/src/runtime/time/wheel/`. I could copy the code over from there into tokio-util which will presumably fix it, but that feels a bit sad. Any suggestions?

**Comment by Darksonn** [comment]
If there are fixes in the Tokio wheel, then please do copy them over.

**Comment by isabelleatkins** [comment]
I've got a PR for this here: https://github.com/tokio-rs/tokio/pull/5630

**Comment by fwojtan** [comment]
I think that while the specific panic has been fixed, this issue is still present in tokio_util 0.7.8. 

Using that version, I run the below code and see the following panic:

`
use tokio::time::Duration;
use tokio_util::time::DelayQueue;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let mut queue = DelayQueue::new();
    tokio::time::pause();
    tokio::time::sleep(std::time::Duration::from_millis(1 << 36)).await;
    let _key = queue.insert_at("foo", tokio::time::Instant::now() + Duration::from_secs(10));
}
`

`
thread 'main' panicked at 'invalid deadline; err=Invalid', src/main.rs:9:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/1.70.0/library/core/src/panicking.rs:67:14
   2: tokio_util::time::delay_queue::DelayQueue<T>::insert_idx
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-util-0.7.8/src/time/delay_queue.rs:670:30
   3: tokio_util::time::delay_queue::DelayQueue<T>::insert_at
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-util-0.7.8/src/time/delay_queue.rs:550:9
   4: delayqueue::main::{{closure}}
             at ./src/main.rs:9:16
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/1.70.0/library/core/src/future/future.rs:125:9
   6: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:541:57
   7: tokio::runtime::coop::with_budget
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/coop.rs:73:5
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:541:25
  10: tokio::runtime::scheduler::current_thread::Context::enter
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:350:19
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:540:36
  12: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:615:57
  13: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  14: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:615:27
  15: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:530:19
  16: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:154:24
  17: tokio::runtime::runtime::Runtime::block_on
             at /opt/rust/registry/src/git.datcon.co.uk-91de7a0a7768d16b/tokio-1.28.2/src/runtime/runtime.rs:302:47
  18: delayqueue::main
             at ./src/main.rs:9:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/1.70.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

This panic also occurs in release mode:
`
thread 'main' panicked at 'invalid deadline; err=Invalid', src/main.rs:9:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/1.70.0/library/core/src/panicking.rs:67:14
   2: tokio_util::time::delay_queue::DelayQueue<T>::insert_at
   3: <core::pin::Pin<P> as core::future::future::Future>::poll
   4: tokio::runtime::scheduler::current_thread::Context::enter
   5: tokio::macros::scoped_tls::ScopedKey<T>::set
   6: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
   7: tokio::runtime::runtime::Runtime::block_on
   8: delayqueue::main
`

Please reopen, thanks

**Comment by fwojtan** [comment]
I've discussed with @isabelleatkins and think I'm happy that the panic I'm seeing here is because the DelayQueue's internal representation of the time is only updated when it is polled. 

If this is a deliberate design choice then maybe this just needs some more detail in the documentation around the panic. 

I.e. it promises to panic if 'when' is too far in the future, but it's not obvious at all that the DelayQueue and tokio::time::Instant::now() might disagree with each other about what the time is currently.

**Comment by lleadbet** [comment]
I want to clarify one thing noted- is the max duration still the same called out in the original ticket, or has it be increased/reduced/etc? 

> If a DelayQueue exists for more than 2^36 milliseconds (2 years 64 days 21 hours 7 minutes 4.7856432 seconds)...

**Comment by isabelleatkins** [comment]
It now doesn't panic after any amount of time (well in relation to this bug anyway)

Also, this issue was resolved, and reopened due to a misunderstanding- it can be closed as resolved again.
