### ISSUE TITLE
`JoinSet::join_next` can hang if initial poll occurs on an empty list

### ISSUE THREAD

**Issue by lucacasonato** [tokio-rs/tokio#5835]
**Version**

tokio v1.29.0

**Platform**

macOS arm64

**Description**

When constructing a `JoinSet`, it internally initially has a `None` waker. If `JoinSet::join_next` it is then immediately polled with a waker (for example from a `tokio::spawn`ed task), one would expect the JoinSet to capture this waker so that when a task is spawned onto the `JoinSet`, and this task completes, the original waker to called so that `join_next` is polled again.

This however does not happen due to the following fast path: https://github.com/tokio-rs/tokio/blob/080d52902fc0e72af210e753df0b509731fd9b5d/tokio/src/util/idle_notified_set.rs#L173-L178

This causes the initial poll on an empty `JoinSet` to not caputre any waker, and thus for the waker passed to `join_next` to never be woken when a spawned future resolves. This causes this combination of tasks to deadlock, unless `join_next` is manually polled.

The fast path only works correctly if something is spawned onto the `JoinSet` _before_ `join_next` is polled for the first time.

I unfortunately have not been able to write a minimal test case yet, but @bartlomieju is on it. We'll update this issue once we have a test case.

**Comment by lucacasonato** [comment]
Retracted, `join_next` returns `Poll::Ready(None)` when the `JoinSet` is empty (and correctly does not store the waker). We were violating the contract 🙃

**Comment by klkvr** [comment]
hey @Darksonn I've just hit this bug myself and was wondering if you could provide a bit more context on why this shouldn't be fixed? to me it's not about getting woken when something got pushed but about getting woken if any of the tasks were completed (even if the tasks were spawned and pushed after we've registered the waker)

simplied version of my usecase is pretty much this:
```rust

struct Worker {
    tasks: JoinSet<()>,
}

impl Worker {
   fn push_task(&mut self) {
        self.tasks.spawn(async { ... });
   }
}

impl Future for Worker {
    fn poll(...) {
        while let Poll::Ready(Some(result)) = pending.poll_join_next(cx) {}
    }
}

struct Manager {
   workers: FuturesUnordered<Worker>,
}

impl Future for Manager {
   fn poll(...) {
       for worker in self.workers.iter_mut() {
           // maybe call worker.push_task()
       }
       
       self.workers.poll_next_unpin(cx);
   }
}
```

here if initially all `Worker`s don't have any tasks, the waker won't be registered on the first poll, causing them to never get polled again because
