### ISSUE TITLE
the current scheduling strategy seems to be unable to wake up idleWorker promptly

### ISSUE THREAD

**Issue by ghost** [tokio-rs/tokio#5854]
The part of the Golang scheduler related to stealing, as well as unbinding P and M, is designed with the complex purpose of waking up P promptly when there are tasks. Tokio's weak wakep, in certain situations, fails to awaken P promptly, and in extreme cases ,some workers remain idle and cannot be awakened for a short period.

 I analyzed the scheduling logic of golang, libgo and tokio.
Golang uses M with no bound P implements timely wake-up of P.  (generate background threads up to a maximum of 50% of the total number of Ps)
Libgo balances tasks using load-balancing threads at a 1ms interval. 
In theory, Tokio has issues with its wake-up logic. Of course, there is no perfect scheduling, so making do with it is also acceptable.

**Comment by Darksonn** [comment]
You're not giving enough details at all. What is P and M? What is the main difference between the two strategies?

**Comment by carllerche** [comment]
Yes, even I, who is quite familiar with the go scheduler internals do not understand what you are saying. I do know what P and M are but you are making vague quality claims without specifying any details at all. What does “weak” mean? What specific differences are you taking about?

**Comment by Noah-Kennedy** [comment]
I'm in the same boat as Carl. It might be worth taking some more time and word count to explain in a bit more detail here what you are referring to.

**Comment by sxstd001** [comment]
Here's an example of an extreme scenario from a theoretical perspective:
**TOKIO**:
// Only 8 threads: P1-P4 are working, p5-p8 are stealing, and there are no idle workers; // p represents a worker;
At this point:
❶ P1 captures 128 timer tasks but fails to wake up an idle P because there are stealers present;
p5-p8: Let's assume they all missed P1;

❷ P5-P8 join the idle queue;
P5-P7 epoll_wait;
P8 -> Scans for tasks -> But fails to wake up (assuming at this time P2 has completed all tasks and is currently stealing);

❸ <repeat: extreme case:
P2 -> Finds tasks -> Fails to wake up (assuming at this time P3 is in stealing state);
P3 -> Finds tasks -> Fails to wake up (assuming at this time P4 is in stealing state);
P4 -> Finds tasks -> Fails to wake up (assuming at this time P2 is in stealing state);
repeat>

▪ Extreme case: P5-P8 are observing, P1-P3 are self-sustaining;
▪ The key point is that waking up batch tasks one by one needs to consider the presence of stealers, which slows down the process.

**Golang:**
// Only 8 threads: P1-P4 are working, p5-p8 are stealing, and there are no idle workers; // M represents a thread;
At this point:
❶ P1 captures 128 timer tasks but fails to wake up an idle P because there are no idle workers;
p5-p8: Let's assume they all missed P1;

❷ P5-P8 unbind from P and become M5-M8; P5-P8 transition to idle state;

❸ M5-M8 scan P1-P4:
a. If M5-M8 finds tasks and can bind with P5-P8, go to the top; if not, idle workers are awakened by P1-P4;
b. During the scanning process of M5-M8, P2 may poll 4 tasks and directly wake up P5-P8 and bind them (create new threads M9-M12), rendering M5-M8 futile.

**Comment by carllerche** [comment]
That’s not actually how the Tokio scheduler works though (same with the golang one too afaik). There are safeguards to ensure tasks that are stealing don’t “miss” wakes as you put it. 

I’m not sure what you are referencing with Ms scanning Ps. Can you link the relevant code?
