### ISSUE TITLE
AsyncBufRead more buf control

### ISSUE THREAD

**Issue by JPaja** [tokio-rs/tokio#6064]
**Is your feature request related to a problem? Please describe.**
I'm exploring solutions how to write more advanced version of AsyncBufReadExt::read_until  with multi byte delimiter (`&[u8]`), and not consuming delimiter itself (keeping delimiter data at start of internal buffer).

Problematic scenario is when delimiter is contained in multiple packets for example:
```
Delimiter: [0x01,0x02,0x03,0x04]
packet1: [0x00,0x00,0x01,0x02]
packet2: [0x03,0x04,0x00,0x00]
expected result: consumed: [0x00,0x00], internal buffer: [0x01,0x02,0x03,0x04,0x00,0x00]
```

What is problematic here is I have to `consume` whole packet1 before calling `poll_fill_buf` because it requires empty internal buffer to call read again, and I cannot restore bytes consumed `(0x01, 0x02)`

**Describe the solution you'd like**
The least painful solution would be to add `poll_extend_fill_buf` function where it would call read and extend those bytes into internal buf. 
In above case that could be solution if internal buffer size is larger or equal than delimiter.

**Describe alternatives you've considered**
Other solution could be  to add some way of restoring read bytes by inserting into internal buffer.
In my case insert to position 0 delimiter after I finish read_until that consumes delimiter. Also other buffer manipulations could be useful like appending, clearing, etc

**Comment by Darksonn** [comment]
Unfortunately, this is not something we can change. The current trait supports things such as [`StreamReader`][1], which do not easily allow you to append more to the buffer.

Tokio chose to use this design for the trait because that mirrors `std::io::BufRead`, which has the same limitations.

Please check out the [`tokio_util::codec`][2] module instead, which can do things like this.

[1]: https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/io/stream_reader.rs
[2]: https://docs.rs/tokio-util/latest/tokio_util/codec/index.html
