### ISSUE TITLE
Provide `tokio::spawn_handle` as a version of `tokio::spawn` that returns a handle to the task

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#626]
## Problem

Spawning tasks results in a computation that happens in the background decoupled from the spawner. It is common to want to get the result of the computation or to be able to cancel the task from the spawner.

## Proposal

Add the following free function:

```rust
tokio::spawn_handle<T>(future: T) -> SpawnHandle<T::Item, T::Error>
where T: Future: Send + 'static,
           T::Item: Send,
           T::Error: Send,
{ ... }
```

The function would live in `tokio-executor` and be re-exported in `tokio`.

### Bonus

Provide an equivalent function for `tokio::runtime::current_thread` that does not require `Send` (re-exported from `tokio-current-thread`.

## Open questions

Should the function be called `background`?

**Comment by liranringel** [comment]
As discussed in #640, panics should not propagate from the executor, because tasks are the equivalent of "async threads".
`spawn_handle` is like the async equivalent to `JoinHandle::join`, that let us know if a panic has occurred. Hence we want `spawn_handle` to provide that information.
It will require a change in `spawn_handle` signature. If we stick to `JoinHandle::join` style, it may look like:
```rust
tokio::spawn_handle<T>(future: T) -> SpawnHandle<Result<T::Item, T::Error>, Box<Any + Send + 'static>>
where T: Future: Send + 'static,
           T::Item: Send,
           T::Error: Send,
{ ... }
```
And perhaps we want to include the word `join` in the new api for better discoverability. Mabye `spawn_joinable`?

**Comment by carllerche** [comment]
Superseded by #1180
