### ISSUE TITLE
tokio-async-await: Idiomatic way to spawn on other runtimes

### ISSUE THREAD

**Issue by nemosupremo** [tokio-rs/tokio#627]
## Version

tokio-async-await 0.1.2

## Description

Currently to spawn async functions, you need to call `tokio::run_async`, which internally calls `tokio::run` with a shim. However there isn't an API available if you want to spawn tasks on a specific runtime. You could do rip out the code in `tokio::run_async` and do something like:

```rust
let my_fut = backward::Compat::new((async move {
    while let Some(msg) = await!(receiver.next()) {
        resp_out = match await!(resp_out.send(msg.unwrap())) {
            Ok(v) => v,
            Err(e) => {
                return
            }
        };
    }
// });
}).map(|_| Ok(())));

some_runtime.spawn(my_fut).unwrap()
```

However, this doesn't look super clear (`.map(|_| Ok(()))`?). (I understand, that in this example, I could just use `.map()`). I wanted to take a stab at writing an API but I wasn't sure how that should be implemented, or if its somehow already on the timeline for when the async/await API continues to stabilize.

**Comment by carllerche** [comment]
Off the top of my head, I think it would be something like:

Add the following trait in `tokio-async-await` and include it in the prelude:

```rust
trait SpawnAsync<T> {
    fn spawn_async(&mut self, task: T) -> SpawnError;
}
```

`SpawnError` is  https://docs.rs/tokio/0.1.8/tokio/executor/struct.SpawnError.html.

Implement that trait for all the various types that have `spawn` fns. These impls would also go in the `tokio-async-await` crate. `Future03` references the `Future` trait from std nightly.

```rust
impl<T: Future03<Item = ()> + Send + 'static> SpawnAsync<T> for tokio::runtime::Runtime {
    fn spawn_async(&mut self, task: T) {
        use futures_util::future::FutureExt;
        use crate::async_await::compat::backward;

        let future = future.map(|_| Ok(()));
        self.spawn(backward::Compat::new(future))
    }
}
```

The `map(|_| Ok(()))` is fine here because the future is bound by `()` (does not return a value).

There are quite a number of tasks that should have `SpawnAsync` implemented for them. I'd search for types that already impl `Executor`.

Note that, we should impl `SpawnAsync` for `tokio::runtime::current_thread` types even though those do not impl `Executor` (due to the `Send` requirement).

Hope this helps.

**Comment by carllerche** [comment]
This should no longer be an issue as master is being updated to use std::future.
