### ISSUE TITLE
current-thread: consider catching panics in spawned tasks

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#640]
Currently, tasks spawned onto the current-thread executor will not have panics handled. This means if a task panics, the entire executor will shutdown.

This is not necessarily the expected behavior. Tasks should be as independent as possible. The threadpool handles panics.

This may require a breaking change.

**Comment by liranringel** [comment]
I would expect that a panic will propagate further.
It looks like panics are simply ignored in `ThreadPool`. Perhaps that's the behavior we want to change?

**Comment by carllerche** [comment]
I consider tasks equivalent to "async threads". When a thread panics, the process is not aborted. In my mind, the same applies here.

**Comment by liranringel** [comment]
I see.
But `Executor::spawn` does not provide information about panics, unlike `JoinHandle::join` that does.
Mabye the new api `spawn_handle` should let us know if a panic occurred? It could solve your comment here: https://github.com/tokio-rs/tokio/pull/638/files#r218594157
However, I don't know how that could be easily implemented since `spawn_handle` uses `Executor::spawn`.

**Comment by carllerche** [comment]
@liranringel  It should be possible to support detecting a panic w/ `spawn_handle`. Would you mind adding your comment to the `spawn_handle` issue?

**Comment by carllerche** [comment]
This is done on master.
