### ISSUE TITLE
No option to choose buffer capacity for copy_bidrectional

### ISSUE THREAD

**Issue by dd-dreams** [tokio-rs/tokio#6454]
**Is your feature request related to a problem? Please describe.**
`io::copy_bidirectional` uses it's own sizes (8KB) without caring about the reader/writer buffer capacities.

**Describe the solution you'd like**
A new function like `io::copy_buf` only for bidirectional writes/reads is requested if possible.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by RRRadicalEdward** [comment]
What about a new `copy_bidirectional_with_buf_size` that would accept the buffer size as the last argument? Or maybe,  would it be better to accept two buffer sizes for reader and writer buffers. 

I don't think it's possible to have a new function like [io::copy_buf](https://docs.rs/tokio/latest/tokio/io/fn.copy_buf.html) because in the case of `copy_bidirectional` we need to set the buffer size for writer stream as well and there isn't `tokio::io::AsyncBufWrite`.

**Comment by RRRadicalEdward** [comment]
It seems like some time ago people agreed that we could just make another function that would take the size but the naming is the issue: https://github.com/tokio-rs/tokio/pull/3572#issuecomment-818564613

**Comment by RRRadicalEdward** [comment]
There is [File::set_max_buf_size](https://docs.rs/tokio/latest/tokio/fs/struct.File.html#method.set_max_buf_size). We can take it as a reference and name the new function like `copy_bidirectional_with_max_buf_size`.

**Comment by dd-dreams** [comment]
> What about a new `copy_bidirectional_with_max_size` that would accept the buffer size as the last argument?

This would be even better since it will allow raw FD instead of BufReader.

**Comment by dd-dreams** [comment]
I think a better name for the function is `copy_bidirectional_sized`.

**Comment by RRRadicalEdward** [comment]
> I think a better name for the function is copy_bidirectional_sized.

No really sure on this one because, `_sized` postfix isn't used in contexts of custom buffer sizes.

It's hard to say what best name for it is. I thought also about `copy_bidirectional_with_capacity`, similar to [`BufReader::with_capacity`](https://doc.rust-lang.org/std/io/struct.BufReader.html#method.with_capacity).

**Comment by Darksonn** [comment]
Yeah, I don't think `_sized` works. As for `_with_capacity`, it isn't really great either. That naming is usually used for collections, which this is not.

**Comment by dd-dreams** [comment]
Maybe `copy_bidirectional_buf`? Similar to `copy_buf`.

**Comment by RRRadicalEdward** [comment]
> Maybe `copy_bidirectional_buf`? Similar to `copy_buf`.

It might not be the best solution since we wouldn't pass a `buf`, but the internal `buf` size

**Comment by dd-dreams** [comment]
I guess something similar to your original suggestion like`copy_bidirectional_with_size` would be feasible.

**Comment by RRRadicalEdward** [comment]
@Darksonn  Does `copy_bidirectional_with_size` sounds good to you?

**Comment by Darksonn** [comment]
Yes.
