### ISSUE TITLE
Box futures passed to `block_on` in debug mode 

### ISSUE THREAD

**Issue by ibraheemdev** [tokio-rs/tokio#6673]
Tokio currently [does this in `spawn`](https://github.com/tokio-rs/tokio/blob/master/tokio/src/task/spawn.rs#L171) but not `block_on`. For large async main functions this can lead to stack overflows in debug mode, especially on Windows. See https://github.com/astral-sh/uv/pull/4851 for example.

**Comment by mox692** [comment]
I think we can add similar checks for `block_on` as well.

@Darksonn 
Do you have a better idea other than just adding Future's size check logic like [#4009](https://github.com/tokio-rs/tokio/pull/4009)? (I'm wondering since it seems that you said [such a possibility](https://github.com/tokio-rs/tokio/pull/4009#issuecomment-890160839) in that PR.)

**Comment by Darksonn** [comment]
There are some other approaches, but they are more complicated. Basically, the idea is to avoid passing the future by ownership through many function calls. Instead, you create a kind of owned pointer that references the future object on the stack, and then you pass the pointer all the way down to the function that moves it to the heap.

But I'm happy to add a size check for now.
