### ISSUE TITLE
must_use for JoinHandle::abort_handle

### ISSUE THREAD

**Issue by incker** [tokio-rs/tokio#6761]
Hello !

Can you please make `#[must_use]` macro for function `JoinHandle::abort_handle(..) `

Because sometimes i mix up functions `JoinHandle::abort_handle(..) ` and `JoinHandle::abort(..) `

Forward thank you!

**Comment by sainad2222** [comment]
Hey @Darksonn @incker, I can give it a go. Can you help me understand the expected behavior? From what I understood we just need to put must_use macro on abort_handle so that it gives warning whenever we are not using the value returned from abort_handle and the issue here is there is a case of mixup when folks are using abort_handle instead of abort and ignoring the return value?
