### ISSUE TITLE
Improve .github/ISSUE_TEMPLATE.md 

### ISSUE THREAD

**Issue by kpp** [tokio-rs/tokio#679]
https://github.com/tokio-rs/tokio/pull/567#discussion_r212793316

## Description

We may improve it by changing or adding these lines to .github/ISSUE_TEMPLATE.md:

```
$ cargo tree -i -p tokio - show the version of tokio crate only
$ cargo tree -p tokio - show all tokio crates (the subcrates may be useful for debugging too)
```

**Comment by tobz** [comment]
I tried both of these commands out, and they give less useful output than the current suggested command.  Since they pin to `tokio` as the root crate, it ignores other tokio crates that are imported discretely.

I'm going to close this because I think the current solution is the most optimal for the time being.  If `cargo tree` had a mode that did grep for you, but also showed dependency tree, that would be most optimal.
