### ISSUE TITLE
`tokio::io::simplex` read/write data not equality

### ISSUE THREAD

**Issue by chessnokov** [tokio-rs/tokio#6877]
**Version**

```
└── tokio v1.40.0
    └── tokio-macros v2.4.0 (proc-macro)
│   ├── tokio v1.40.0 (*)
└── tokio v1.40.0 (*)
```

**Platform**

`Linux fedora 6.11.0-63.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep 15 17:48:54 UTC 2024 x86_64 GNU/Linux`

**Description**

Written data to `SimplexStream` not equality reading data 

[short summary of the bug]

[code sample that causes the bug]

```rust
#[cfg(test)]
mod tests {
    use tokio::{
        io::{simplex, AsyncWriteExt, AsyncRead, AsyncReadExt},
        select,
    };

    #[tokio::test]
    async fn read_write() {
        const PATTERN: &[u8] = &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0xA];

        let (mut receiver, mut sender) = simplex(197);

        let mut buffer = vec![0; PATTERN.len()];

        for _ in 0..1024 * 2 {
            select! {
                n = receiver.read_exact(buffer.as_mut_slice()) => {
                    n.unwrap();
                    assert_eq!(buffer.as_slice(), PATTERN);
                }
                result = sender.write_all(PATTERN) => {
                    result.unwrap()
                }
            }
        }
    }
}
```

I expected to see this happen: [explanation]

Test passed

Instead, this happened: [explanation]

```
assertion `left == right` failed
  left: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
 right: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

**Comment by Darksonn** [comment]
The `write_all` and `read_exact` methods are *not* cancel safe. It's possible for second branch to partially write `PATTERN`, and then get aborted when the first branch completes. 

To give a simpler example, imagine that the pattern is just `[0, 1]`, and that the simplex cannot fit more than 3 bytes.

1. Iteration 1. A full write of `PATTERN` succeeds. Buffer now contains `[0,1]`.
2. Iteration 2 part 1. The `write_all` call partially writes the buffer, but does not finish as the buffer is full. The buffer now contains `[0,1, 0]`.
3. Iteration 2 part 2. The `read_exact` call reads two bytes. This removes the first `[0,1]` from the buffer and the buffer now contains `[0]`.
4. Iteration 3. A full write of `PATTERN` succeeds. Buffer now contains `[0,0,1]`.
5. Iteration 4. The `read_exact` call reads two bytes. This removes the first `[0,0]` from the buffer and the buffer is now empty. The assertion fails because the data is not equal to the pattern.

In iteration 2, it is the `read_exact` call that succeeded, but the `write_all` call still partially wrote the buffer. This is consistent [with the documentation](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWriteExt.html#method.write_all):

> Cancel safety
>
> This method is not cancellation safe. If it is used as the event in a [tokio::select!](https://docs.rs/tokio/latest/tokio/macro.select.html) statement and some other branch completes first, then the provided buffer may have been partially written, but future calls to write_all will start over from the beginning of the buffer.
