### ISSUE TITLE
`AsyncFd` should use `AsFd` rather than `AsRawFd`

### ISSUE THREAD

**Issue by cramertj** [tokio-rs/tokio#6984]
As described in [the I/O safety RFC](https://rust-lang.github.io/rfcs/3128-io-safety.html):

> An I/O operation is valid if the raw handles ([RawFd](https://doc.rust-lang.org/stable/std/os/fd/type.RawFd.html), [RawHandle](https://doc.rust-lang.org/stable/std/os/windows/io/type.RawHandle.html), and [RawSocket](https://doc.rust-lang.org/stable/std/os/windows/io/type.RawSocket.html)) it operates on are values explicitly returned from the OS, and the operation occurs within the lifetime the OS associates with them. Rust code has I/O safety if it’s not possible for that code to cause invalid I/O operations.

[`AsyncFd` currently accepts an `AsRawFd`](https://docs.rs/tokio/latest/tokio/io/unix/struct.AsyncFd.html) and then performs I/O operations on the underlying file descriptor without requiring the user to use `unsafe`. I believe this violates I/O safety, since the user can pass in any `RawFd` (which can be constructed safely) and perform file operations on it outside its lifetime.

`AsyncFd` should, I think, accept an [`AsFd`](https://doc.rust-lang.org/std/os/fd/trait.AsFd.html) instead, as `AsFd` provides a [`BorrowedFd`](https://doc.rust-lang.org/std/os/fd/struct.BorrowedFd.html) which guarantees (by way of being `unsafe` to construct) that the file descriptor is within its lifetime.

**Comment by Darksonn** [comment]
I'm not going to treat this as a real issue because it is not a real issue.

If you pass an invalid fd to AsyncFd, what's going to happen is that epoll_ctl returns EBADF and then we handle that error properly. If you close the fd while it's in the AsyncFd, then epoll is going to give us some errors, which we also handle properly. The only "risk" is that somebody elsewhere wrote unsafe code that's incorrect if the fd gets registered with an unrelated epoll instance. AsyncFd doesn't really perform any dangerous operations; for example, it does not let you close the fd.

The cost involved with a migration to fix this is far too big. It's going to stay as-is.
