### ISSUE TITLE
Is a codec required to handle the receiving of multiple messages over the same socket ?

### ISSUE THREAD

**Issue by George3d6** [tokio-rs/tokio#712]
I guess this is more of a question rather than a bug, but, the documentation makes this very unclear to me so I thought it worth asking as an issue.

I've seen tokio being used to read and write messages over the same socket (without closing the connection) in a manner whereby you can "chain" functions that process some input and deliver some output.

As is the case with the `lines` and the `copy` functionality provided by `tokio::io`.

Can this type of functionality be achieved by using Tokio's `read_*` functionality rather than by writing a custom codec ?

Is it possible to implement something similar to `lines` using `read_until` or must one implement the Codec from scratch ?

Take, for example, the following usecase:

Get some data using `read_until` (to look for some specific separator) -> Then, after that data is received and process read some more data using `read_fixed` -> Then, write some data back -> Then, poll that same socket for new input (which is then handled by the read_until closure)

Is this something that necessitates a custom Codec ? The example on the website (the chat) seem to imply this. But, in that case, I fail to see why the `read_*` functionality is needed at all.

**Comment by tobz** [comment]
Generally speaking, tokio is a _framework_.  The things it provides are abstract and meant to be used as building blocks.

`Framed` and `Codec` are there to help you to wrap a socket (or other `Async[Read|Write]` types) and move from a byte-oriented stream to a message-oriented stream.  They support both the `Stream` and `Sink` interfaces so you can get messages out and put messages back in without too much fuss.

Now, if your application is advanced enough, and you need to write your own custom types for interacting with I/O, you might reach for `tokio::io` and the helpers it contains.  I do this in my own application — [synchrotron](github.com/nuclearfurnace/synchrotron) — although technically I could use a a `Framed`/`Codec` set up for most of my codec need.  I simply chose to use the `tokio::io` helpers directly because I have some unique cases (read N messages from a socket, write batches of messages at a time instead of one, etc) and working with the `Framed` interface would be a little too limited.

**Comment by George3d6** [comment]
The link is broken (https://github.com/tokio-rs/tokio/issues/github.com/nuclearfurnace/synchrotron)... I'd love to see the code examples, since the only "stream" examples tokio has involve writing your own Codecs... or, at least, so it seems from their website and the example page here.

**Comment by George3d6** [comment]
ah, nvm, the repo is still there, the link had the tokio page copy-pasted onto it for some reason: https://github.com/nuclearfurnace/synchrotron

**Comment by George3d6** [comment]
Welp, that code seems pretty complex... as in, there's a few abstraction layer under the `facade` that make it quite hard to figure out how you are actually handling the stream of bytes.

But maybe I'm just bad at reading code.

Still, if anyone has an example of how to read + write on the same socket, without closing the connection, without using a codec and without using a pre-build codec like Lines, and, instead, using io primitives like `read_until` and `read_fixed`, it would be welcome.

I feel like it ought to be the main usecase for someone using tokio so it's pretty weird if it's not documented anywhere.

**Comment by kpp** [comment]
@George3d6 basically you don't need to call functions `read`, `read_until`, `read_exact`. You need to implement your codec with traits `Encoder` and `Decoder`. You are looking for this method: https://docs.rs/tokio-codec/0.1.1/tokio_codec/trait.Decoder.html#tymethod.decode

The algo is:
1. Open socket
2. Wrap socket with Codec
3. Split wrapped socket into 2 parts: reading part and writing part.
 here goes "multithreading":
4.a for each incoming `message` from reading part process it
4.b for each outgoing `message` from your queue(basically mpsc) send into writing part.

It is a common pattern for almost all applications written with tokio.

Here is a very detailed example https://github.com/jgallagher/tokio-chat-example/blob/master/tokio-chat-server/src/main.rs#L185 . Please read it very very carefully. There are a lot of comments and it will help you a lot with learning tokio.

Good luck!

**Comment by George3d6** [comment]
Well... that's an example using the out-of-maintenance version of tokio.

Also, it seems to hide the relevant logic for my specific problem in the: tokio_chat_common extern crate

Which is my main issue, every "well detailed example" seem to be 400+ lines of code split into different modules usually using an older version of the library with an API that's incompatible with this tokio.

But, there seems to be an "up to date" implementation of that same chat-application on the Tokio website (which is what I'd use as an example to implement a codec).

My question was more to do withe wether a codec is needed at all.

**Comment by kpp** [comment]
> Well... that's an example using the out-of-maintenance version of tokio.

It does not matter. The solution method is the same.

> My question was more to do withe wether a codec is needed at all or if I could just chain the tokio::io functionality.

Codec is optiona. Yes you can chain tokio::io calls.

**Comment by George3d6** [comment]
Well... then, back to my original question, are there any examples of chaining tokio::io calls to get the same results as with processing a tcp stream via a codec ? When I tried it out  ( chaining read_until, read_fixed and write_all ) it resulted in the connection just closing once all the steps were executed.

**Comment by tobz** [comment]
I'm not sure if there's an existing example, because it's mostly an advanced approach.

It sounds like you're just not looping over your connections, which is consistent with your description.

It might be easier if you join us in [Gitter](https://gitter.im/tokio-rs/tokio) and can show us the code you're working with.  These teaching moments that require going over iterations of code can be a bit drawn out over a GitHub issue.

**Comment by tobz** [comment]
I think using codecs are conceptually simpler because there's ultimately less complex code to write.  If you can read your message out of a `&[u8]`, and turn it into `&[u8]`, then `Framed`, and all of the examples of it, get you going pretty quickly.  You can basically write synchronous code in the encoder/decoder.

I think the trouble you're having is a testament to the barebones approach being harder because it involves the culmination of understanding a lot of pieces: futures chaining, futures vs streams, splitting, stream iteration, holding your tx/rx components to avoid being dropped, etc etc.

It's all stuff worth learning, and at some point, you can't write sufficiently complex applications _without_ understanding it, but if I had to teach someone one or the either, and they were brand new, I'd teach them about codecs and `Framed`.  Just my two cents.

We'll help you get your problem one way or the other. :)

**Comment by kpp** [comment]
> Well... then, back to my original question, are there any examples of chaining tokio::io calls to get the same results as with processing a tcp stream via a codec? 

`tokio-codec` was implemented to simplify the code.

> I'm not sure if there's an existing example, because it's mostly an **advanced approach**.

That's true.

> Maybe it's just me being stupid and not knowing how to rtfm, but I've had no issues with this kind of "basic" functionality with similarly aimed libraries like boost asio or python asyncio.

It looks like `x y problem`. Have a look at http://xyproblem.info/ . Please try to explain what you need to implement. Don't tell us "how" (like with `read_*` functions) but "what" you want to implement.

**Comment by George3d6** [comment]
Hmh, ok, let me try and phrase it as a problem in that case:

How does one write a server that accepts connections and for each of those connections:

a) Fills a buffer until the character `@` is parsed
b) Fills a buffer with the next 320 bytes written on the connection (as in, written to the connection after @ is parsed)
c) Writes back those exact 320 bytes (stored before in a buffer) AND goes back to the top to (a) on that same connection (as in, it leaves the connection open)

**Comment by kpp** [comment]
As I told you before (https://github.com/tokio-rs/tokio/issues/712#issuecomment-433855919) :

> The algo is:
> 1. Open socket
> 2. Wrap socket with Codec
> 3. Split wrapped socket into 2 parts: reading part and writing part.
> here goes "multithreading":
> 4.a for each incoming message from reading part process it
> 4.b for each outgoing message from your queue(basically mpsc) send into writing part.

The most "tricky" part here is Codec. Please read https://docs.rs/tokio-codec/0.1.1/tokio_codec/trait.Decoder.html#tymethod.decode  and https://github.com/jgallagher/tokio-chat-example/blob/master/tokio-chat-server/src/main.rs .

And read source code for LinesCodec: https://github.com/tokio-rs/tokio/blob/master/tokio-codec/src/lines_codec.rs#L126

So you don't need to call `read_*` functions since they are encapsulated inside Codec for you.

**Comment by carllerche** [comment]
I opened an issue here https://github.com/tokio-rs/doc-push/issues/86 to track.

Unfortunately, the answer is that combinator functions are weak right now and hopefully, once async/await lands, it will get easier.

Until then, you will want to implement a codec by hand and probably implement your custom future (the tokio website has docs on how to do that).

I'm going to close this issue, but we can continue the discussion here: https://github.com/tokio-rs/doc-push/issues/86
