### ISSUE TITLE
What would it take to build tokio for bare metal on ARM?

### ISSUE THREAD

**Issue by theronic** [tokio-rs/tokio#752]
What would it take to run Tokio on bare metal, and how small could the resulting binary be?

I'm keen to make a bespoke kernel that can act as an OS on a Raspberry Pi and later on, an ESP32 microcontroller with minimal code changes. Tokio seems like a good async abstraction for this, esp. if I want to interact with an MQTT broker to send some data.

I took a gander through the transitive dependencies, and I'm not seeing anything ominous like `libc`. Pardon me if this is already possible.

**Comment by carllerche** [comment]
`libc` is a requirement via `mio`.

The first step to run on bare metal would be to see if [mio](http://github.com/carllerche/mio/) could be made to do so.

Also, this this a `no_std` environment?

**Comment by tobz** [comment]
Ooooh, this is super interesting!  Definitely keep us informed of your progress. :D

Following on Carl's comments, it seems like you would have to make sure `mio` works on your target environment.  It's hard to even imagine what this would look like on an embedded platform like an ESP32 because it'd have to be pretty specific, right? As in, depending on whatever software you ran, you'd likely need a selector (`mio` parlance for the underlying async I/O framework i.e. `epoll`) specific to your set-up... setting up interrupt routines to do the "socket data is here!" notifications into `mio` to drive the async I/O.

Very interesting project indeed!

**Comment by carllerche** [comment]
Given that the work would first have to happen in `mio`, I am going to close this issue. That said, feel free to continue to comment here with questions / thoughts (we get notified by email).
