### ISSUE TITLE
Require changelog entry as part of PR

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#767]
One of the more time consuming parts of releasing new crates is updating the CHANGELOG files. I propose that the CHANGELOG files are updated as part of PRs.

This would require that maintainers check that the PR updates the changelog as needed. If the edit is missing, the maintainer can either request the change or apply it directly to the PR.

Most PRs should be tracked as part of the change log, but not all need a dedicated line. We should figure out a policy for how to best maintain the changelog.

For example:

```md
# unreleased

* Introduce some feature, short description (#123).
* Fix a serious bug causing things to explode (#456).
* Miscellaneous bug fixes (#888, #5123, #1).
* Documentation tweaks (#6, #235, #987).
```

So, bigger changes get their own entry and smaller things would get batched up.

Thoughts?

cc @tobz @jonhoo @seanmonstar @stjepang @ipetkov

**Comment by stjepang** [comment]
I tried doing something similar in Crossbeam. In the end, I gave up because it was  less of a hassle doing `git log --oneline crate-version.. -- .` and updating the changelog once per release than updating the changelog on every PR. YMMV, though.

Would it help to have a script that suggest changelog updates? Suppose you could just type `cargo unreleased` and it would dump a list of unreleased changes per tokio crate.
