### ISSUE TITLE
Confusing error message from tokio-uds::UnixListener::bind()

### ISSUE THREAD

**Issue by ufoscout** [tokio-rs/tokio#855]
## Version
tokio 0.1.13
tokio-codec 0.1.1
tokio-uds 0.2.4 

## Platform
Linux ufo-laptop-1 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Subcrates
tokio-uds

## Description
The error returned when a UDS socket cannot be created is too generic and does not help to identify the issue.
E.g.,
```rust
UnixListener::bind("/a/path/that/does/not/exists").unwrap()
```
this produces the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, message: "Not a directory" }
```

Due to the fact that our application uses many directories for its configuration, it took some time to figure out what was the issue. We would have instead expected something like:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cannot bind UDS socket to path [/a/path/that/does/not/exists]: Os { code: 20, kind: Other, message: "Not a directory" }
```

**Comment by LucioFranco** [comment]
Looks like this error originates within `mio-uds` and not within tokio proper https://github.com/tokio-rs/tokio/blob/master/tokio-uds/src/listener.rs#L26 might be worthwhile to open an issue in that project?

**Comment by carllerche** [comment]
And that `mio-uds` probably returns the error from `std`.

@ufoscout I agree with you that the error is not very helpful. However, there isn't much that *we* can do. This would have to be fixed in `std`. But, I don't see *how* it can be fixed without adding overhead on top of what the syscall gives us.

If my analysis is wrong, feel free to open the issue again or comment here and I will re-open it.
