### ISSUE TITLE
Consider an instrumentation API to explicitly create unrooted spans or manually create the parent / child relationship

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#920]
Follow up from discussion in #907.

It seems like there are cases when the subscriber will be unable to observe the correct parent / child relationship. In these cases, it might be desirable to have an API to make the relationship between spans explicit.

**Comment by hawkw** [comment]
Regardless of how we want to determine parent-child relationships implicitly (based on the current span at time of creation, or at time of first entry?), I think having an API for setting them _explicitly_ is definitely a good idea. 

As I see it, we have two options: 
1. We pass the parent as a parameter to `Subscriber::new_span`. This would mean that:
  - This enforces statically that spans may only have 0-1 parents. We've made this assumption elsewhere, so I think this is the Right Thing --- the `follows_from` API is intended for cases where spans are related to several other spans.
  - When creating spans using the `span!` macro (the common case), the user will have to specify the parent in the macro (since the macro is responsible for calling `new_span`). This isn't a serious problem, but it does mean adding another optional argument to the `span!` macro, which is kind of a shame IMO:
  ```rust
   let foo = span!("foo");
   let bar = span!("bar", parent: foo);
  ```
  - This parameter would probably be optional, and when it isn't passed, the subscriber could default to whatever it considers the "current" span. This means we would need separate ways of indicating whether the default should be used or the span should be created as a root, all of which seem ugly to me:
    * separate `Subscriber::new_span` and `Subscriber::new_root` functions (adds even more bloat to the subscriber API, not great)
    * `Subscriber::new_span` takes an `Option<Option<Span>>` parameter where the outer option indicates "no parent" and the inner option indicates "default parent" (this is Just Awful).
    * A new type like 
      ```rust
      enum Parent {
          Explicit(Span),
          Current,
          None,
      }
      ```
      (would probably need to be wrapped in a struct for forward-compat). This is the option that communicates the semantics the most clearly IMO, but would involve a bunch of code.
    * Make the macro the one responsible for choosing the default if no explicit parent is provided. It could say something like 
      ```rust
      dispatcher::with(|current| current.new_span(
          meta, 
          fields, 
          Some(current.current_span(),
      ));
      ```
      However, this would mean adding a notion of a current span to the `Subscriber` API. AFAIK there's been some discussion of doing this anyway: https://github.com/tokio-rs/tokio/issues/907#issuecomment-465654414, https://github.com/tokio-rs/tokio-trace-nursery/issues/16#issuecomment-466492836. Personally, I think this is the best choice if we end up adding a function like that.
2. We add a new function to the `Subscriber` API, something like `record_parent`.  `Span`s could have a function which records another span as their parent by calling the subscriber function.
  - This gives us an API surface like
     ```rust
     let foo = span!("foo");
     let bar = span!("bar").parent(foo);
     ```
  - However, there's nothing stopping this function from being called multiple times, and this would leave how to handle that up to the subscriber --- it could overwrite the previous parent, silently do nothing, or even panic --- and I don't think that's ideal...

Personally, I'm inclined to think that the first option (taking the parent at `new_span` time) is probably the better choice, but I'm open to be convinced otherwise. @carllerche and @davidbarsky, any thoughts?

**Comment by carllerche** [comment]
Passing in the info as part of `Subscriber::new_span` sounds correct. However, at this point I would suggest defining a "arguments" struct. This would also allow us to pass in further args in the future.

**Comment by carllerche** [comment]
This also raises the question: Do we want other fns on `Subscriber` to take an "arguments" struct instead of listing the arguments out (for forwards compat)?

**Comment by hawkw** [comment]
@carllerche passing an "args" struct to `new_span` definitely sounds like the right thing to me --- we did something like that in an earlier prototype iteration with the [`Attributes` struct](https://github.com/hawkw/tokio-trace-prototype/commit/1711eaa8b284eceec7da6c63b57f33e014e8010c#diff-d889522a69162ab94aa0257ca505508dR47).

re: having other `Subscriber` functions take similar structs, I think several of these functions already basically do this --- they're invoked with opaque types which the subscriber can only interact with via method calls (`Event`, `ValueSet`). It might be worthwhile to consider giving all the subscriber functions a similar treatment, but on the other hand, that seems like a lot of boilerplate. I don't know if functions like `enter`/`exit`, or the ref-counting functions (`clone_span`/`drop_span`) will ever be likely to be passed something other than an `Id`, but it might be worth guarding against breaking changes even if they're not likely there...

**Comment by carllerche** [comment]
My initial cut is that it isn't worth adding indirect to `enter` / `exit` as those should stay simple...

`field::ValueSet` *could* count as an argument struct, but only if we don't intend to reuse that struct for any other reason except passing args to `record`.

**Comment by hawkw** [comment]
@carllerche 
> My initial cut is that it isn't worth adding indirect to `enter` / `exit` as those should stay simple...
👍 

> `field::ValueSet` _could_ count as an argument struct, but only if we don't intend to reuse that struct for any other reason except passing args to `record`.

Currently, it's also used internally in the `Event` struct, but `Event` doesn't actually _expose_ the `ValueSet`, just forwards to its `record` method...

**Comment by carllerche** [comment]
@hawkw that *feels* like an argument for `record` to have its own argument struct? What if there are values that only make sense for `record` and not `event` (or `new_span`)?

**Comment by hawkw** [comment]
That's fair. We can add a record struct with the span ID and valueset, then. In that case, we can also make most of the `ValueSet` functions other than the constructor `pub(crate)`, I think.

**Comment by carllerche** [comment]
Do you think that `span` should be moved into the struct? Most other fns (except event) take `span: &Span`. For consistency, it *might* be nice to have:

```rust
fn record(&self, span: &Span, record: &Record);

fn event(&self, span: &Span, event: &Event);
```

wdyt? I don't care strongly either way.

**Comment by hawkw** [comment]
@carllerche why would `event` take a `Span` parameter? The current span? My understanding is that it's up to the subscriber to track the current span.

I don't have an opinion on passing the span separately or not. It might be slightly more ergonomic to continue passing it separately.

As a side note, we already have a trait `field::Record`, so I think that an arguments struct to the `Subscriber::record` function should probably not share a name with the trait...one of them ought to be renamed.

**Comment by carllerche** [comment]
@hawkw oops yeah, sorry disregard that bit about event & span.

**Comment by carllerche** [comment]
@hawkw and yes, the naming conflict is bad... open to alternative naming ideas.

**Comment by hawkw** [comment]
@carllerche I've sketched out what an API for setting the parent of a new span (using a `NewSpan` type) might look like: https://github.com/tokio-rs/tokio/pull/923

**Comment by carllerche** [comment]
Looks good at a glance.

What do you think about having different constructors for `NewSpan` instead of defining a `Parent` type? Like `Span::new` (parent is current span), `Span::with_parent(...)`, `Span::new_root(...)`? For the macro, that would translate to `parent: None` for root, no parent key for "current", and parent: foo to explicitly set a parent.

Just a thought.

I don't *love* the name `NewSpan`, but it is better than anything else I can come up with right now... one option (I don't know if I like it and I know you will hate me...) would be to rename `Span` -> `Id` and `NewSpan` -> `Span`... naming is hard.

I probably wouldn't bother with `fn has_parent()` as `parent().is_some()` is  nice enough.

**Comment by hawkw** [comment]
> Looks good at a glance.
> 
> What do you think about having different constructors for `NewSpan` instead of defining a `Parent` type? Like `Span::new` (parent is current span), `Span::with_parent(...)`, `Span::new_root(...)`? For the macro, that would translate to `parent: None` for root, no parent key for "current", and parent: foo to explicitly set a parent.

That was my original thought as well, but (without having tried it) it seemed to play less nice with the macros --- more of the macro cases would have to actually be constructing spans rather than just expanding to other macro cases with more parameters. I'm still willing to try it...

> I don't _love_ the name `NewSpan`, but it is better than anything else I can come up with right now... one option (I don't know if I like it and I know you will hate me...) would be to rename `Span` -> `Id` and `NewSpan` -> `Span`... naming is hard.

https://github.com/hawkw/tokio-trace-prototype/issues/126 :P

**Comment by carllerche** [comment]
Ideally we would design the -core APIs w/o worrying too much about the macros. If the macro is too complex, lets consider other options.

yeah yeah (I have been known to change my mind). That said, I don't know if I like `span::Id` that much...

**Comment by hawkw** [comment]
@carllerche not to bikeshed _too_ much over this, but what do you think of `tokio-trace-core` having `span::Id` and `span::Attributes`? That way we can reserve the name `Span` for the span handle type in `tokio-trace` and don't need to rename either of the `tokio-trace-core` types...

**Comment by hawkw** [comment]
@carllerche okay, you were right --- I removed the `Parent` type and replaced it with a set of constructors, and the impact on the macros was not that bad after all. I'll open a final PR as soon as we finish bikeshedding over names. :)

**Comment by carllerche** [comment]
For consistency w/ other Tokio parts, perhaps we could use "handle"? Either `span::Handle` or `SpanHandle` (instead of `Id`).

`span::Attributes` seems fine.

**Comment by hawkw** [comment]
@carllerche IMO `Id` is more descriptive and has precedent with distributed tracing systems that refer to "span IDs", but I'm willing to use `Handle` if you think it's better.

**Comment by carllerche** [comment]
I don't care that much. So you pick.

It's not so much a span ID though, because it might be a pointer right?

**Comment by hawkw** [comment]
PR #923 is reviewable now, btw --- sorry for the delay!
