### ISSUE TITLE
[tokio-io] got block or debug assert panic when using tokio::fs::File::poll_read

### ISSUE THREAD

**Issue by Sasasu** [tokio-rs/tokio#976]
### Version and Platform
Rust playground stable
Rust playground beta
Rust playground nightly

### Subcrates
tokio-fs

### Description

I am writing a tap/tun based application,  use `tokio::sync::mpsc` to shard data between UDP socket and tun interface in one thread.

I tried this code:
```rust
match file.poll_read(&mut buffer)? {
    Async::Ready(size) => {
        println!("{}", size);
    }
    Async::NotReady => unreachable!("not ready detected, it works"),
}
```
when use `std::fs::File` or `tokio::fs::File` to open file, got block
when use `libc::open(file, libc::O_NONBLOCK)`, got debug assert panic

the paly ground link: https://play.rust-lang.org/?edition=2018&gist=c9bbedb14eeffe88aed1247db1cfa409

**Comment by tobz** [comment]
This is expected, and I'll try to explain why:

`tokio::fs::File` is based on `std::fs::File`.  Since there's no currently available cross-platform asynchronous file I/O library, Tokio has taken the path of providing blocking I/O that runs on worker threads which don't service futures.

As an example, you start a normal Tokio runtime and your task tries to interact with `tokio::fs::File`.  Under the hood, the thread pool runtime will take that thread running the task, and "move" it into a dedicated area.  That thread will now only run that task, which means we can do blocking I/O on it without stalling other tasks.

Since we do I/O as blocking, we're never going to hit a situation where `poll_read` returns `NotReady`, and that's why your example behaves like it does.

There's an external crate -- [tokio-file](https://github.com/asomers/tokio-file) -- that tries to provide that, but it doesn't support Linux (yet).  That would be one way that you could attempt to do truly asynchronous I/O, but it would require some manual implementation of `libaio` for `mio`.
